export const ALL=[
{cat:"actie",tier:"party",t:"Doe je beste imitatie van de speler links van je tot iemand lacht.",m:1,p:2},
{cat:"actie",tier:"party",t:"Spreek de komende 2 minuten alleen in vragen.",m:1,p:2},
{cat:"actie",tier:"party",t:"Bestel je volgende drankje in een compleet ander accent.",m:1,p:2},
{cat:"actie",tier:"party",t:"Geef een willekeurige speler een eerlijk compliment en een eerlijke roast.",m:1,p:2},
{cat:"actie",tier:"party",t:"Doe 10 seconden je beste danspasje.",m:1,p:2},
{cat:"actie",tier:"party",t:"Praat 1 minuut in een verzonnen taal met volle overtuiging.",m:1,p:2},
{cat:"actie",tier:"party",t:"Geef een dramatische speech van 30 sec over waarom dit de beste vakantie ooit is.",m:1,p:2},
{cat:"actie",tier:"party",t:"Geef je drankje een naam en stel het serieus voor aan de groep.",m:1,p:1},
{cat:"actie",tier:"party",t:"Loop een rondje om de tafel met een live sportverslag van jezelf.",m:1,p:2},
{cat:"actie",tier:"party",t:"Laat de groep een geluid kiezen dat je maakt elke keer dat je drinkt.",m:2,p:3},
{cat:"actie",tier:"party",t:"Vraag de dichtstbijzijnde groep om een high five voor de overwinning.",m:2,p:3},
{cat:"actie",tier:"party",t:"Groet 3 vreemden alsof je ze al jaren kent.",m:2,p:3},
{cat:"actie",tier:"party",t:"Vraag bij de bar om een glas water voor mijn beste vriend en wijs naar een vreemde.",m:2,p:3},
{cat:"actie",tier:"party",t:"Voer een nep-telefoongesprek over een feest dat niet bestaat.",m:2,p:3},
{cat:"actie",tier:"party",t:"Vraag een vreemde om een bijnaam voor je te verzinnen.",m:2,p:3},
{cat:"actie",tier:"party",t:"Maak een video waarin de hele groep slow-motion doet.",m:1,p:2},
{cat:"actie",tier:"party",t:"Laat een onbekende raden uit welk land je komt en speel het mee.",m:2,p:3},
{cat:"actie",tier:"party",t:"Doe een minuut alsof je een influencer bent die deze plek reviewt.",m:2,p:3},
{cat:"actie",tier:"party",t:"Sla je vuist op tafel en schreeuw RONDE VOOR IEDEREEN - bestel dan gewoon 1 water.",m:2,p:3},
{cat:"actie",tier:"party",t:"Vertel de barman dat je jarig bent en vraag om een kaarsje.",m:2,p:3},
{cat:"actie",tier:"party",t:"Doe alsof je een slechte buikspreker bent met je hand als pop, 30 sec.",m:1,p:2},
{cat:"actie",tier:"party",t:"Spreek 2 minuten in rijm - elke zin moet rijmen.",m:2,p:3},
{cat:"actie",tier:"party",t:"Sta op en applaudisseer keihard voor de speler tegenover je.",m:1,p:2},
{cat:"actie",tier:"party",t:"Noem de volledige naam van elke speler aan tafel in 15 sec. Elke fout = 1 slok.",m:1,p:2},
{cat:"actie",tier:"party",t:"Doe alsof je een bokswedstrijd commentaar geeft tussen 2 spelers naar keuze.",m:1,p:2},
{cat:"actie",tier:"party",t:"Zing Happy Birthday keihard naar een willekeurige vreemde aan de bar.",m:2,p:3},
{cat:"actie",tier:"party",t:"Loop naar de dichtsbijzijnde tafel en vraag of je 1 minuut mag aanschuiven.",m:2,p:3},
{cat:"actie",tier:"party",t:"Sta op en doe alsof je je ex belt voor een serieus gesprek waar iedereen bij is.",m:2,p:3},
{cat:"actie",tier:"party",t:"Vertel een verhaal over je vakantie maar elk detail is gelogen.",m:1,p:2},
{cat:"actie",tier:"party",t:"Rap 20 seconden over het drankje dat je nu drinkt.",m:2,p:3},
{cat:"actie",tier:"party",t:"Doe 1 minuut alsof je doof bent - communiceer alleen met gebaren.",m:1,p:2},
{cat:"actie",tier:"party",t:"Ga staan en geef een toast op de meest random persoon.",m:1,p:2},
{cat:"actie",tier:"party",t:"Doe alsof je een toerist bent en vraag de weg naar een plek die niet bestaat.",m:2,p:3},
{cat:"actie",tier:"party",t:"Loop naar de bar en bestel met overdreven handgebaren, zonder te praten.",m:2,p:3},
{cat:"actie",tier:"party",t:"Spreek de komende ronde alleen in superlatieven.",m:1,p:2},
{cat:"actie",tier:"party",t:"Ga staan, draai een rondje en wijs iemand aan: die persoon drinkt 3.",m:1,p:2},
{cat:"actie",tier:"party",t:"Doe een weerbericht over de stemming aan tafel.",m:1,p:2},
{cat:"actie",tier:"party",t:"Ga naar een andere tafel en vertel dat je van de kwaliteitscontrole bent. Geef een review.",m:2,p:4},
{cat:"actie",tier:"party",t:"Schreeuw IK HEB GEWONNEN en ga weer rustig zitten.",m:1,p:2},
{cat:"actie",tier:"party",t:"Neem je drankje op als een shotgun.",m:2,p:3},
{cat:"actie",tier:"party",t:"Vertel de barman je hele levensverhaal in 30 seconden.",m:2,p:3},
{cat:"actie",tier:"party",t:"Doe alsof je een detective bent en ondervraag een medespeler over hun avond.",m:1,p:2},
{cat:"actie",tier:"party",t:"Sta op en maak een selfie met de meest random persoon die je ziet.",m:2,p:3},
{cat:"actie",tier:"party",t:"Spreek 3 minuten alleen in de derde persoon over jezelf.",m:1,p:2},
{cat:"actie",tier:"party",t:"Probeer een vreemde ervan te overtuigen dat je een beroemdheid bent.",m:2,p:4},
{cat:"actie",tier:"party",t:"Proost met elke tafel in een straal van 5 meter.",m:2,p:3},
{cat:"actie",tier:"party",t:"Doe alsof je dronken bent en vraag een vreemde om hulp.",m:2,p:3},
{cat:"actie",tier:"party",t:"Maak een compleet liedje van 20 sec over de vakantie.",m:2,p:3},
{cat:"actie",tier:"party",t:"Fluister alles de komende 2 minuten.",m:1,p:2},
{cat:"actie",tier:"party",t:"Ga naar de bar en probeer je drankje gratis te krijgen met enkel charme.",m:3,p:5},
{cat:"actie",tier:"party",t:"Doe alsof je aan het bellen bent en vertel hardop een absurd verhaal.",m:1,p:2},
{cat:"actie",tier:"party",t:"Wissel van stoel met een andere tafel - vraag beleefd of het mag.",m:2,p:3},
{cat:"actie",tier:"party",t:"Doe een staande ovatie voor het drankje van de speler naast je.",m:1,p:2},
{cat:"actie",tier:"party",t:"Zeg tegen een vreemde: Jij herinnert me aan iemand beroemds en verzin wie.",m:2,p:3},
{cat:"actie",tier:"party",t:"Organiseer een mini Mexican wave met je tafel.",m:1,p:2},
{cat:"actie",tier:"party",t:"Loop naar een andere tafel en doe alsof je de ober bent. Neem een bestelling op.",m:2,p:4},
{cat:"actie",tier:"party",t:"Praat de komende 3 minuten met een zwaar accent.",m:1,p:2},
{cat:"actie",tier:"party",t:"Doe het geluid van een bekende automelodiedoorbel tot iemand het raadt.",m:1,p:2},
{cat:"actie",tier:"party",t:"Ga staan en vertel een sprookje over een speler naar keuze. Max 30 sec.",m:1,p:2},
{cat:"actie",tier:"party",t:"Leg je hoofd 30 seconden op de schouder van een medespeler alsof je slaapt.",m:1,p:2},
{cat:"actie",tier:"party",t:"Doe alsof je een YouTuber bent en open een unboxing van je drankje.",m:1,p:2},
{cat:"actie",tier:"party",t:"Vraag een vreemde om een groepsfoto en doe alsof jullie een boyband zijn.",m:2,p:3},
{cat:"actie",tier:"party",t:"Noem 10 landen in 15 seconden. Per gemiste: 1 slok.",m:1,p:2},
{cat:"actie",tier:"party",t:"Doe alsof je een natuur-documentaire vertelt over het gedrag van je groep.",m:1,p:2},
{cat:"actie",tier:"party",t:"Maak een paper airplane van een servet en gooi het naar een andere tafel met een boodschap.",m:2,p:3},
{cat:"actie",tier:"flirty",t:"Geef de speler die je het aantrekkelijkst vindt een compliment, of drink 3.",m:2,p:4},
{cat:"actie",tier:"flirty",t:"Doe alsof je een datingprofiel-video opneemt, 20 seconden.",m:2,p:4},
{cat:"actie",tier:"flirty",t:"Stuur een flirterig emoji naar het 5e contact in je telefoon.",m:2,p:3},
{cat:"actie",tier:"flirty",t:"Doe je meest verleidelijke loop naar de bar en terug.",m:2,p:4},
{cat:"actie",tier:"flirty",t:"Fluister iets liefs in het oor van de speler links van je.",m:2,p:3},
{cat:"actie",tier:"flirty",t:"Beschrijf je droomdate in 3 zinnen.",m:1,p:2},
{cat:"actie",tier:"flirty",t:"Geef een speler naar keuze een schattige bijnaam die de rest van de avond blijft.",m:1,p:2},
{cat:"actie",tier:"flirty",t:"Loop naar een onbekende en zeg: Sorry, mijn vrienden zeiden dat ik je moest aanspreken.",m:2,p:4},
{cat:"actie",tier:"flirty",t:"Stuur een voice note naar je crush met alleen Heyyyy met 5 y.",m:2,p:3},
{cat:"actie",tier:"flirty",t:"Doe je meest charmante glimlach 10 sec naar de speler tegenover je. Niet lachen.",m:1,p:2},
{cat:"actie",tier:"flirty",t:"Beschrijf je ideale partner maar het moet klinken als een vacaturetekst.",m:1,p:2},
{cat:"actie",tier:"flirty",t:"Vraag een onbekende om te raden of je single bent.",m:2,p:3},
{cat:"actie",tier:"flirty",t:"Geef de speler rechts een 10/10 review als date. Wees specifiek.",m:2,p:3},
{cat:"actie",tier:"flirty",t:"Stel je voor alsof je op een datingshow zit.",m:1,p:2},
{cat:"actie",tier:"flirty",t:"Knipoog naar een vreemde en zwaai langzaam.",m:2,p:3},
{cat:"actie",tier:"flirty",t:"Stuur een DM naar iemand met alleen een vuur-emoji. Screenshot naar de groep.",m:2,p:4},
{cat:"actie",tier:"flirty",t:"Vertel de groep wie je het laatst hebt gestalkt op Instagram.",m:2,p:3},
{cat:"actie",tier:"flirty",t:"Doe alsof je een onbekende ten huwelijk vraagt. Ga op 1 knie.",m:3,p:5},
{cat:"actie",tier:"flirty",t:"Schrijf een pickup line op een servet en geef het aan een vreemde.",m:2,p:4},
{cat:"actie",tier:"flirty",t:"Laat een speler je Tinder-bio herschrijven en zet het live.",m:3,p:5},
{cat:"actie",tier:"flirty",t:"Fluister je ruikt lekker naar de speler links.",m:2,p:3},
{cat:"actie",tier:"flirty",t:"Doe je beste filmzoen-imitatie met je hand. De groep beoordeelt.",m:1,p:2},
{cat:"actie",tier:"flirty",t:"Ga naar een vreemde en vraag: Ben jij mijn Tinder-date?",m:2,p:4},
{cat:"actie",tier:"flirty",t:"Stuur je ex een GIF zonder context. Screenshot naar de groep.",m:3,p:5},
{cat:"actie",tier:"flirty",t:"Maak oogcontact met een onbekende en houd het 10 sec vol.",m:2,p:3},
{cat:"actie",tier:"flirty",t:"Beschrijf de persoon links van je als Tinder-profiel. Swipe de groep links of rechts?",m:1,p:2},
{cat:"actie",tier:"flirty",t:"Stuur Ik mis je naar het 8e contact in je telefoon. Screenshot.",m:3,p:5},
{cat:"actie",tier:"flirty",t:"Vraag een onbekende: Op een schaal van 1-10, hoe goed zie ik eruit vanavond?",m:2,p:4},
{cat:"actie",tier:"flirty",t:"Maak een list met de top 3 hotste mensen in de ruimte. Lees hardop voor.",m:2,p:4},
{cat:"actie",tier:"flirty",t:"Zeg tegen een vreemde: Je hebt iets van mijn ex - vertel niet wat.",m:2,p:3},
{cat:"actie",tier:"flirty",t:"Doe alsof je verlegen bent en vraag de barman om zijn nummer voor een vriend.",m:2,p:4},
{cat:"actie",tier:"flirty",t:"Stuur een spraakbericht naar iemand: Bro ik denk dat ik verliefd ben. Geen context.",m:3,p:5},
{cat:"actie",tier:"flirty",t:"Vertel een onbekende dat je net gedumpt bent en dat je een knuffel nodig hebt.",m:2,p:4},
{cat:"actie",tier:"flirty",t:"Doe 15 sec je beste kijk mij eens sexy zijn-loop door het terras.",m:2,p:3},
{cat:"actie",tier:"flirty",t:"Stuur een selfie naar je crush met per ongeluk en delete het NIET.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Laat een speler 1 minuut jouw telefoon beheren. Alles mag.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Bel een willekeurig contact: Ik wilde even zeggen dat ik trots op je ben. Hang op.",m:2,p:3},
{cat:"actie",tier:"extreme",t:"Stuur je laatst gebelde contact een spraakbericht waarin je een liedje zingt.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Laat iemand een tekst typen die jij als story plaatst.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Bel het 3e contact in je telefoon en vraag of ze single zijn.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Post Ik ben verliefd als story zonder context.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Geef je telefoon aan de groep voor een telefoon-raid van 30 seconden.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Stuur een spraakbericht naar je ouders: Ik heb een tattoo genomen.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Laat een willekeurige speler beslissen wat jouw volgende drankje wordt.",m:2,p:3},
{cat:"actie",tier:"extreme",t:"Bel je baas en zeg: Ik heb een idee waar we het maandag over moeten hebben. Hang op.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Stuur We moeten praten naar het 4e contact in je telefoon. Wacht op reactie.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Post een Instagram story met locatie en Vermist: mijn waardigheid.",m:2,p:4},
{cat:"actie",tier:"extreme",t:"Laat de groep kiezen welk nummer je belt. Je moet minstens 20 sec volhouden.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Stuur je ouders: Kan ik even bellen? Is niet erg maar... en dan 5 min niks.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Vertel een vreemde dat je op de vlucht bent en vraag of je even mag zitten.",m:2,p:4},
{cat:"actie",tier:"extreme",t:"Bel een willekeurig contact en huil nep 10 seconden. Dan: Grapje. Hang op.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Stuur je meest recente selfie naar je ex met Kijk wat je mist.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Geef je ontgrendelde telefoon 2 minuten aan de speler die je het minst vertrouwt.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Bel het laatst gebelde contact en zeg alleen: Het is gedaan. Het is voorbij. Hang op.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Stuur een voicenote naar je familiegroep: Ik heb groot nieuws, bel me morgen.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Like de oudste foto van iemand op Instagram die de groep kiest.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Post een poll op je story: Moet ik mijn ex terugberichten? Ja/Nee.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Stuur een random emoji-reeks naar je crush. Geen uitleg.",m:2,p:3},
{cat:"actie",tier:"extreme",t:"Bel een vriend die niet op vakantie is en schep 1 minuut op over hoe vet het is.",m:2,p:3},
{cat:"actie",tier:"extreme",t:"Wissel je Instagram-bio naar iets dat de groep bedenkt. Minimaal 24 uur laten staan.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Stuur Sorry voor gisteren naar het 6e contact. Geen context.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Ga live op Instagram voor 30 sec. Zeg: Ik moet jullie iets vertellen. Sluit af.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Maak een story van de tafel en typ: De liefde van mijn leven zit hier. Tag niemand.",m:2,p:4},
{cat:"actie",tier:"extreme",t:"Stuur een DM naar een bekend persoon op Instagram. De groep kiest het bericht.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Bel je moeder en vraag: Mam, geloof jij in buitenaards leven? Serieus.",m:2,p:3},
{cat:"actie",tier:"extreme",t:"Verander je profielfoto naar een foto die de groep maakt. Nu.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Laat de groep een bericht sturen in een dating-app namens jou.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Bel iemand en doe alsof je een enquete afneemt over vakantiegeluk.",m:2,p:3},
{cat:"actie",tier:"extreme",t:"Stuur Ja, ik doe het naar het 2e contact. Geen context. Wacht op reactie.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Post een foto van je schoen op je story met Nieuwe aanwinst. Gedachten?",m:2,p:3},
{cat:"actie",tier:"extreme",t:"Ga naar een vreemde en zeg: Je hebt iets laten vallen. Als ze vragen wat: Mijn interesse.",m:2,p:4},
{cat:"actie",tier:"extreme",t:"Stuur je ouders een foto van een willekeurige ring en typ Zij zei ja!",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Laat de groep een voice note inspreken die jij naar een contact stuurt.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Open je camera, neem een random foto van de tafel, post het als story: Bewijs.",m:2,p:3},
{cat:"actie",tier:"extreme",t:"Stuur naar een groepschat: Jongens ik ben net aangehouden. Kan iemand bellen? Wacht 2 min. Dan: Grapje.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Bel een willekeurig contact en rap 15 seconden over hen.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Ga naar de barman en zeg: Ik denk dat mijn vriend verliefd op je is. Wijs naar een speler.",m:2,p:4},
{cat:"actie",tier:"extreme",t:"Stuur We zijn klaar. Ik hoop dat je gelukkig wordt. naar het 9e contact.",m:3,p:5},
{cat:"actie",tier:"extreme",t:"Maak een boomerang terwijl je doet alsof je huilt en post het.",m:2,p:4},
{cat:"actie",tier:"extreme",t:"Bel je broer/zus en zeg: Ik moet je iets opbiechten. Wacht 10 sec. Dan: Ik heb je shampoo gebruikt.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Laat de groep een kapsel-idee kiezen en draag het zo de rest van de avond.",m:1,p:2},
{cat:"actie",tier:"genart",t:"Laat de groep je een nieuwe loopstijl geven en loop ermee naar de bar.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Doe je meest genante dansmove in slow motion voor de groep.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Vertel het meest beschamende dat je ooit hebt gegoogeld.",m:2,p:4},
{cat:"actie",tier:"genart",t:"Doe een imitatie van hoe jij loopt als je denkt dat niemand kijkt.",m:1,p:2},
{cat:"actie",tier:"genart",t:"Vertel over de keer dat je het hardst hebt afgegaan.",m:2,p:4},
{cat:"actie",tier:"genart",t:"Maak het grappigste/lelijkste gezicht dat je kunt, groep stemt.",m:1,p:2},
{cat:"actie",tier:"genart",t:"Laat de groep je telefoon-achtergrond kiezen voor de rest van de avond.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Vertel je meest awkward moment met iemands ouders.",m:2,p:4},
{cat:"actie",tier:"genart",t:"Doe het geluid dat je maakt als je alleen thuis bent en je stoot je teen.",m:1,p:2},
{cat:"actie",tier:"genart",t:"Vertel over een keer dat je deed alsof je iemand kende maar geen idee had.",m:1,p:2},
{cat:"actie",tier:"genart",t:"Doe na hoe je danst als je alleen bent. De groep filmt.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Vertel je meest genante Tinder/dating-verhaal.",m:2,p:4},
{cat:"actie",tier:"genart",t:"Laat de groep je WhatsApp-naam veranderen voor 24 uur.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Doe alsof je een model bent op een catwalk. Van de ene kant van het terras naar de andere.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Vertel wanneer je voor het laatst hebt gehuild en waarom.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Doe je meest genante ochtend in de spiegel-ritueel na.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Laat de groep een ringtone voor je kiezen die je de rest van de avond op vol zet.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Vertel het domste dat je ooit voor een crush hebt gedaan.",m:2,p:4},
{cat:"actie",tier:"genart",t:"Ga naar een vreemde en zeg: Sorry, ik dacht dat je iemand anders was. Doe overdreven teleurgesteld.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Vertel de groep je bijnaam op de basisschool.",m:1,p:2},
{cat:"actie",tier:"genart",t:"Doe na hoe je er uitziet als je net wakker wordt.",m:1,p:2},
{cat:"actie",tier:"genart",t:"Laat de groep een foto maken die je als profielfoto moet gebruiken. Nu zetten.",m:3,p:5},
{cat:"actie",tier:"genart",t:"Vertel over je meest awkward moment op school of werk.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Doe je beste sexy gezicht. De groep beoordeelt 1-10. Onder 5 = drink.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Sta op en doe alsof je uitglijdt in slow motion.",m:1,p:2},
{cat:"actie",tier:"genart",t:"Vertel een geheim dat je nog nooit aan iemand hebt verteld.",m:3,p:5},
{cat:"actie",tier:"genart",t:"Doe het geluid van je alarm na en vertel hoeveel keer je snoozet.",m:1,p:2},
{cat:"actie",tier:"genart",t:"Loop als een krab naar de bar en bestel iets.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Laat de groep je Instagram-highlights bekijken en leg elk verhaal uit.",m:2,p:4},
{cat:"actie",tier:"genart",t:"Vertel wat het gênantste is dat je ouders over je weten.",m:2,p:4},
{cat:"actie",tier:"genart",t:"Doe alsof je een slechte goochelaar bent en doe een trick die mislukt.",m:1,p:2},
{cat:"actie",tier:"genart",t:"Vertel wie van de groep je het eerst zou opofferen in een zombie-apocalyps. Leg uit.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Laat de groep een emoji kiezen die je de rest van de avond in elke zin moet gebruiken.",m:1,p:2},
{cat:"actie",tier:"genart",t:"Doe een catwalk maar struikel halverwege. Maak er een show van.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Vertel het gênantste bericht dat je per ongeluk naar de verkeerde hebt gestuurd.",m:2,p:4},
{cat:"actie",tier:"genart",t:"Ga 30 seconden op je knieen zitten en doe alsof je een hond bent. Blaf.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Vertel een embarrassing fact over jezelf die niemand aan tafel weet.",m:2,p:4},
{cat:"actie",tier:"genart",t:"Doe alsof je huilt en omhels de speler naast je. 10 sec.",m:2,p:3},
{cat:"actie",tier:"genart",t:"Laat je google-zoekgeschiedenis van vandaag zien, of drink 5.",m:3,p:5},
{cat:"actie",tier:"social",t:"Maak een selfie met een onbekende op de achtergrond.",m:2,p:3},
{cat:"actie",tier:"social",t:"Post een selfie met een caption die de groep kiest.",m:3,p:5},
{cat:"actie",tier:"social",t:"Laat je DM-verzoeken zien aan de groep.",m:3,p:5},
{cat:"actie",tier:"social",t:"Stuur hey naar je 7e Instagram-volgend.",m:3,p:5},
{cat:"actie",tier:"social",t:"Laat de groep 1 persoon kiezen die je nu volgt op social media.",m:2,p:3},
{cat:"actie",tier:"social",t:"Laat de groep je recente zoekopdrachten zien op Instagram.",m:3,p:5},
{cat:"actie",tier:"social",t:"Maak een boomerang met de hele groep en post het direct.",m:2,p:3},
{cat:"actie",tier:"social",t:"Laat de groep een bericht typen dat jij in je story zet.",m:3,p:5},
{cat:"actie",tier:"social",t:"Toon je schermtijd van vandaag aan de groep.",m:1,p:2},
{cat:"actie",tier:"social",t:"Volg iemand op Instagram die de groep kiest. Stuur direct een DM.",m:3,p:5},
{cat:"actie",tier:"social",t:"Screenshot je batterijpercentage en laatste 5 apps en deel met de groep.",m:1,p:2},
{cat:"actie",tier:"social",t:"Laat je meest recente geopende chat zien zonder te scrollen.",m:2,p:4},
{cat:"actie",tier:"social",t:"Post een story met alleen het woord Help en geen context.",m:2,p:3},
{cat:"actie",tier:"social",t:"Laat zien wie je het vaakst belt. Bel diegene nu.",m:3,p:5},
{cat:"actie",tier:"social",t:"Maak een TikTok met de groep en post het direct.",m:2,p:4},
{cat:"actie",tier:"social",t:"Laat je Spotify top-5 nummers zien. De groep oordeelt.",m:1,p:2},
{cat:"actie",tier:"social",t:"Stuur een voice note met alleen lachen naar het 3e contact.",m:2,p:3},
{cat:"actie",tier:"social",t:"Post een close-up van je gezicht met Goedemorgen terwijl het avond is.",m:2,p:3},
{cat:"actie",tier:"social",t:"Laat de groep 30 sec door je fotorol scrollen. Geen censuur.",m:3,p:5},
{cat:"actie",tier:"social",t:"Reageer met een hartje op de laatste 3 stories die je ziet.",m:2,p:3},
{cat:"actie",tier:"social",t:"Laat de groep een comment plaatsen op je meest recente post.",m:3,p:5},
{cat:"actie",tier:"social",t:"Stuur Wanneer hangen we weer? naar iemand die je al 6 maanden niet hebt gesproken.",m:2,p:3},
{cat:"actie",tier:"social",t:"Post een poll: Ben ik knap? Ja / Absoluut.",m:2,p:4},
{cat:"actie",tier:"social",t:"Laat je notities-app zien aan de groep.",m:2,p:4},
{cat:"actie",tier:"social",t:"Stuur een random meme naar je moeder.",m:1,p:2},
{cat:"actie",tier:"social",t:"Volg je crush op TikTok en like 3 videos achter elkaar.",m:3,p:5},
{cat:"actie",tier:"social",t:"Laat je laatst opgeslagen foto zien.",m:2,p:3},
{cat:"actie",tier:"social",t:"Maak een story-poll: Wie mist mij? met alleen de groep getagd.",m:2,p:3},
{cat:"actie",tier:"social",t:"Laat de groep 1 DM sturen vanaf jouw account naar iemand naar keuze.",m:3,p:5},
{cat:"actie",tier:"social",t:"Post een foto van je voeten met Beach vibes en tag 3 random mensen.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Doe 10 sec je meest verleidelijke blik naar de speler tegenover je. Niet lachen.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Vertel het genantste dat je ooit op een date hebt gedaan, of drink 3.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Doe een sexy dansje van 15 seconden.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Laat je linkerbuur je laatste 3 fotos zien, of drink 4.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Beschrijf wat jouw type is terwijl je iemand in de groep aankijkt.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Doe het overtuigendste lekker eten-geluid dat je in je hebt.",m:2,p:3},
{cat:"actie",tier:"spicy",t:"Met wie in deze groep zou je nog wel een avondje willen? Noem 1, of drink 4.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Ruik de oksel van de speler naast je en geef een eerlijke review.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Beschrijf je slechtste zoen ooit, met details.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Lik de rand van je glas zo verleidelijk mogelijk en proost.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Geef het sexyste serieuze compliment aan de speler rechts van je.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Onthul wat je het laatst hebt opgezocht voor een vriend.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Wie zou je daten als je nu moest kiezen? Noem 1, of drink 3.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Doe na hoe jij flirt. De groep geeft een cijfer.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Doe je beste kreun alsof je in de lekkerste massage zit, 10 sec.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Beschrijf je genantste het ging bijna mis-moment in bed, of drink 4.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Fluister iets gedurfds in het oor van je rechterbuur en herhaal het hardop.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Noem je grootste turn-off op een eerste date, of drink 3.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Doe een lap dance in de lucht (staand, geen contact). Groep beoordeelt.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Vertel het vreemdste dat je ooit aantrekkelijk hebt gevonden aan iemand.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Kies een speler: diegene moet je hand vasthouden tot de volgende ronde.",m:2,p:3},
{cat:"actie",tier:"spicy",t:"Doe alsof je een pornofilm vertelt maar dan als natuur-documentaire.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Geef de speler tegenover je een Good night kiss op de hand.",m:2,p:3},
{cat:"actie",tier:"spicy",t:"Beschrijf je ergste one-night-stand of date in 3 woorden.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Doe je meest verleidelijke kom hier-gebaar naar een speler naar keuze.",m:2,p:3},
{cat:"actie",tier:"spicy",t:"Vertel het gekste seksadvies dat je ooit hebt gekregen.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Doe alsof je een erotische thriller-voiceover inspreekt, 15 sec.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Noem 3 dingen die je nooit zou doen in bed. De groep mag 1 in twijfel trekken.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Ga met je rug tegen een medespeler staan en doe alsof jullie een romcom-poster zijn.",m:2,p:3},
{cat:"actie",tier:"spicy",t:"Vertel wie in de groep het beste zou zijn in een relatie en waarom.",m:2,p:3},
{cat:"actie",tier:"spicy",t:"Doe het geluid van je wekker na maar dan alsof het een orgasme is.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Noem je body count of drink 5. Geen tussenweg.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Beschrijf hoe je zou flirten met de barman als je leven ervan afhing.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Laat de speler links van je een sexy foto van je nemen. Post het in de groep.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Doe alsof je in een parfumreclame zit. 10 sec slow motion.",m:2,p:3},
{cat:"actie",tier:"spicy",t:"Vertel je grootste ik kan niet geloven dat ik dat heb gedaan-moment op vakantie.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Geef een speler naar keuze een nekblaasje. Of drink 5.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Doe je meest verleidelijke bijt-op-je-lip en staar de speler rechts aan, 5 sec.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Vertel eerlijk: wat is het langste dat je zonder seks bent geweest?",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Doe alsof je een massage geeft aan de speler links. 10 sec.",m:2,p:3},
{cat:"actie",tier:"spicy",t:"Noem de speler die je het minst zou daten. Leg uit. Of drink 4.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Doe het geluid van de laatste keer dat je je teen stootte maar maak het sexy.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Vertel het raarste dat je ooit in bed hebt gezegd. Of drink 5.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Zit 30 sec op de schoot van de speler links. Niet lachen.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Noem je guilty pleasure film die je kijkt als niemand het weet.",m:1,p:2},
{cat:"actie",tier:"spicy",t:"Doe alsof je de speler tegenover je filmt voor OnlyFans. En... actie!",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Benoem de 3 meest aantrekkelijke dingen aan de speler rechts.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Vertel je meest cringe sexting-poging ooit. Of drink 5.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Doe 10 sec oogcontact met de speler tegenover je terwijl je heel langzaam je glas leegdrinkt.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Beschrijf je ideale avond met een date maar gebruik alleen geluiden, geen woorden.",m:2,p:4},
{cat:"actie",tier:"spicy",t:"Vertel wat het laatste was waar je je voor schaamde op seksueel gebied. Of drink 5.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Doe je beste morning after-gezicht. De groep beoordeelt.",m:2,p:3},
{cat:"actie",tier:"spicy",t:"Stuur Ik droom soms over je naar het 10e contact. Screenshot.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Kies: zoenen met iemand aan tafel voor 3 sec, of drink 6.",m:3,p:5},
{cat:"actie",tier:"spicy",t:"Fluister de speler links je grootste fantasie in het oor. Die herhaalt het hardop.",m:3,p:5},
{cat:"missie",tier:"party",t:"Laat de groep lachen binnen 15 seconden. Lukt het niet? Drink 3.",m:2,p:4},
{cat:"missie",tier:"party",t:"Doe een perfecte dier-imitatie naar keuze van de groep. Onder 6/10 = mislukt.",m:1,p:3},
{cat:"missie",tier:"party",t:"Noem 5 hoofdsteden in 10 seconden. Per gemiste: 1 slok.",m:1,p:3},
{cat:"missie",tier:"party",t:"Zing het refrein van het laatste nummer dat je luisterde.",m:2,p:4},
{cat:"missie",tier:"party",t:"Doe je beste celebrity-impressie. De groep raadt wie. Fout = drink 2.",m:2,p:4},
{cat:"missie",tier:"party",t:"Vertel 2 waarheden en 1 leugen. De groep raadt de leugen.",m:2,p:4},
{cat:"missie",tier:"party",t:"10 sec oogcontact met de speler tegenover je zonder te lachen.",m:1,p:3},
{cat:"missie",tier:"party",t:"Freestyle rap van 15 sec over de speler links van je.",m:2,p:4},
{cat:"missie",tier:"party",t:"Bedenk de beste pickup line voor de speler rechts van je.",m:2,p:4},
{cat:"missie",tier:"party",t:"Doe een TikTok-dans. Geen idee? Drink 3.",m:2,p:4},
{cat:"missie",tier:"party",t:"Vertel in 10 seconden het meest random feit over jezelf.",m:1,p:2},
{cat:"missie",tier:"party",t:"Doe de stemmen van 3 bekende mensen in 20 seconden.",m:2,p:4},
{cat:"missie",tier:"party",t:"Verzin de beste grappige belediging voor een speler naar keuze.",m:2,p:3},
{cat:"missie",tier:"party",t:"Doe 10 jumping jacks terwijl je het alfabet achterstevoren opzegt.",m:2,p:4},
{cat:"missie",tier:"party",t:"Doe je beste Gordon Ramsay over het drankje van je buurman.",m:1,p:3},
{cat:"missie",tier:"party",t:"Vertel een mop. Lacht niemand, drink 3.",m:2,p:4},
{cat:"missie",tier:"party",t:"Fluister de speler links iets in het oor. Die herhaalt het hardop.",m:1,p:3},
{cat:"missie",tier:"party",t:"Noem 7 biermerken in 10 seconden. Per gemiste: 1 slok.",m:1,p:3},
{cat:"missie",tier:"party",t:"Zing het refrein van een nummer naar keuze van de groep. Niet kennen? Drink 3.",m:2,p:4},
{cat:"missie",tier:"party",t:"Doe een imitatie van de speler rechts. Die beoordeelt 1-10.",m:2,p:4},
{cat:"missie",tier:"party",t:"Noem 5 Portugese woorden in 10 sec. Nep-woorden tellen niet.",m:1,p:3},
{cat:"missie",tier:"party",t:"Maak een geluid als een dolfijn. 10 sec.",m:1,p:2},
{cat:"missie",tier:"party",t:"Verzin een slechte excuusbrief voor de baas in 15 sec.",m:1,p:3},
{cat:"missie",tier:"party",t:"Noem 3 dingen die je ziet die beginnen met de letter van je voornaam. 10 sec.",m:1,p:2},
{cat:"missie",tier:"party",t:"Zing Bohemian Rhapsody maar dan heel de tafel doet mee.",m:2,p:4},
{cat:"missie",tier:"party",t:"Tel achteruit van 30 naar 0 terwijl je om de tafel loopt. Fout = herstart.",m:2,p:3},
{cat:"missie",tier:"party",t:"Doe je beste commentator bij een paardenrace terwijl 2 spelers hun drankje drinken.",m:1,p:3},
{cat:"missie",tier:"party",t:"Noem 10 landen die beginnen met de letter die de groep kiest. 20 sec.",m:2,p:4},
{cat:"missie",tier:"party",t:"Bedenk in 10 sec een bandnaam voor de groep. Iedereen stemt.",m:1,p:2},
{cat:"missie",tier:"party",t:"Maak een compliment voor elke speler in 30 seconden. Timer loopt.",m:2,p:4},
{cat:"missie",tier:"party",t:"Doe alsof je een heel spannend voetbalmoment beschrijft. 15 sec.",m:1,p:3},
{cat:"missie",tier:"party",t:"Balanceer een servet op je neus voor 10 sec. Valt het? Drink 2.",m:1,p:3},
{cat:"missie",tier:"party",t:"Noem alle spelers aan tafel op volgorde van leeftijd. Per fout: 1 slok.",m:1,p:3},
{cat:"missie",tier:"party",t:"Doe het geluid van een racewagen, ambulance en ijscowagen na.",m:1,p:2},
{cat:"missie",tier:"party",t:"Vertel een verhaal in precies 10 woorden. Meer of minder = drink.",m:2,p:3},
{cat:"missie",tier:"party",t:"Doe je beste boze coach-toespraak over de prestaties van de groep.",m:1,p:3},
{cat:"missie",tier:"party",t:"Noem 5 cocktails in 8 sec.",m:1,p:3},
{cat:"missie",tier:"party",t:"Maak het geluid van een printer die vastloopt.",m:1,p:2},
{cat:"missie",tier:"party",t:"Eet iets op de meest dramatische manier mogelijk.",m:1,p:2},
{cat:"missie",tier:"party",t:"Vertel een heel eng spookverhaal in 15 sec.",m:2,p:3},
{cat:"missie",tier:"party",t:"Doe een perfecte slow-motion replay van hoe je je drankje pakt.",m:1,p:2},
{cat:"missie",tier:"party",t:"Gooi een munt op: kop = jij drinkt 3, munt = de hele tafel drinkt 1.",m:1,p:3},
{cat:"missie",tier:"party",t:"Doe je beste Cristiano Ronaldo SIUUUUU. Groep beoordeelt.",m:1,p:3},
{cat:"missie",tier:"party",t:"Noem elke speler + hun drankje in 15 sec. Per fout: drink.",m:2,p:4},
{cat:"missie",tier:"party",t:"Bedenk een slogan voor het terras waar je zit.",m:1,p:2},
{cat:"missie",tier:"party",t:"Doe een moonwalk naar de bar.",m:2,p:3},
{cat:"missie",tier:"party",t:"Doe het geluid van elk seizoen: wind, regen, vogels, krekel.",m:1,p:2},
{cat:"missie",tier:"party",t:"Noem de verjaardag van elke speler. Per fout: 1 slok.",m:2,p:4},
{cat:"missie",tier:"party",t:"Ga staan en hou een motivational speech van 15 sec alsof je een TED Talk geeft.",m:2,p:3},
{cat:"missie",tier:"party",t:"Doe 15 sec air guitar alsof je voor 50.000 man staat.",m:1,p:3},
{cat:"missie",tier:"flirty",t:"Geef de speler tegenover je het beste compliment dat je kunt verzinnen.",m:1,p:3},
{cat:"missie",tier:"flirty",t:"Verzin de slechtste pickup line die je kunt bedenken. De groep stemt.",m:1,p:3},
{cat:"missie",tier:"flirty",t:"Doe een filmzoen-scene (in de lucht) met de speler links.",m:2,p:4},
{cat:"missie",tier:"flirty",t:"Beschrijf de speler rechts als filmkarakter. Wie is het en waarom?",m:1,p:3},
{cat:"missie",tier:"flirty",t:"Stuur een selfie naar je crush. Nu.",m:3,p:5},
{cat:"missie",tier:"flirty",t:"Maak oogcontact met een vreemde en glimlach 5 sec.",m:2,p:3},
{cat:"missie",tier:"flirty",t:"Fluister je bent speciaal in het oor van de speler die het langst single is.",m:2,p:3},
{cat:"missie",tier:"flirty",t:"Beschrijf de speler links als Hinge-profiel in 10 sec.",m:1,p:3},
{cat:"missie",tier:"flirty",t:"Ga naar een vreemde en zeg: Mijn vrienden vinden je leuk. Wijs naar de tafel.",m:2,p:4},
{cat:"missie",tier:"flirty",t:"Noem 3 celebrities die je zou daten in 5 sec.",m:1,p:2},
{cat:"missie",tier:"flirty",t:"Vertel de beste first date die je ooit hebt gehad. 15 sec.",m:1,p:3},
{cat:"missie",tier:"flirty",t:"Maak een flirterig praatje met je eigen hand. 10 sec.",m:2,p:3},
{cat:"missie",tier:"flirty",t:"Bedenk de meest cringe Hey voor een datingapp.",m:1,p:3},
{cat:"missie",tier:"flirty",t:"Doe je aantrekkelijke foto-pose. Iemand maakt de foto.",m:1,p:3},
{cat:"missie",tier:"flirty",t:"Beschrijf in 10 sec hoe je ideale partner ruikt.",m:1,p:2},
{cat:"missie",tier:"extreme",t:"Bel een willekeurig contact en zing 10 sec happy birthday.",m:3,p:5},
{cat:"missie",tier:"extreme",t:"Daag de speler tegenover je uit voor een chug race. Verliezer drinkt nog 3.",m:2,p:4},
{cat:"missie",tier:"extreme",t:"Drink je drankje met je ogen dicht. Morsen = extra slok.",m:1,p:3},
{cat:"missie",tier:"extreme",t:"Laat de groep een foto van je nemen en stuur het naar je ouders zonder context.",m:3,p:5},
{cat:"missie",tier:"extreme",t:"Eet een shotje zout van je hand.",m:2,p:3},
{cat:"missie",tier:"extreme",t:"Doe alsof je flauwvalt op het terras. Houd het 10 sec vol.",m:2,p:4},
{cat:"missie",tier:"extreme",t:"Daag een vreemde uit voor steen-papier-schaar. Verliezer drinkt.",m:2,p:4},
{cat:"missie",tier:"extreme",t:"Doe 20 push-ups op het terras. Nu.",m:2,p:4},
{cat:"missie",tier:"extreme",t:"Bel een willekeurig contact en zeg alleen: Ik weet wat je hebt gedaan. Hang op.",m:3,p:5},
{cat:"missie",tier:"extreme",t:"Drink je drankje door een rietje dat de groep op een rare plek plaatst.",m:2,p:3},
{cat:"missie",tier:"extreme",t:"Ga liggen op de grond voor 10 sec. Sta dan op alsof er niks is gebeurd.",m:2,p:4},
{cat:"missie",tier:"extreme",t:"Laat een ijsklontje in je shirt vallen en laat het smelten.",m:2,p:3},
{cat:"missie",tier:"extreme",t:"Doe een handstand tegen de muur (of poging).",m:2,p:4},
{cat:"missie",tier:"extreme",t:"Bel een willekeurig contact en fluister: Ze weten het. Hang op.",m:3,p:5},
{cat:"missie",tier:"extreme",t:"Neem het drankje van de speler naast je en drink het in 1 teug leeg.",m:2,p:4},
{cat:"missie",tier:"extreme",t:"Ga naar de bar en vraag om jullie geheime menu.",m:2,p:3},
{cat:"missie",tier:"extreme",t:"Daag de speler links uit: wie kan het langst zijn adem inhouden? Verliezer drinkt 3.",m:1,p:3},
{cat:"missie",tier:"extreme",t:"Spuit water in je gezicht alsof het een reclame is.",m:2,p:3},
{cat:"missie",tier:"extreme",t:"Doe alsof je belt en vertel dat je net een miljoen hebt gewonnen.",m:1,p:2},
{cat:"missie",tier:"extreme",t:"Balanceer je drankje op je hoofd, sta op en ga weer zitten. Morsen = drinken.",m:2,p:4},
{cat:"missie",tier:"genart",t:"Doe je meest cringe TikTok-dans voor de hele groep.",m:2,p:4},
{cat:"missie",tier:"genart",t:"Laat je ochtendgezicht zien. De groep beoordeelt.",m:1,p:3},
{cat:"missie",tier:"genart",t:"Doe een imitatie van hoe je loopt na 10 biertjes.",m:1,p:3},
{cat:"missie",tier:"genart",t:"Vertel het domste dat je ooit in een groepschat hebt gestuurd.",m:2,p:4},
{cat:"missie",tier:"genart",t:"Doe alsof je verdwaald bent en vraag een vreemde waar het strand is terwijl je er naast zit.",m:2,p:3},
{cat:"missie",tier:"genart",t:"Doe je ik ben boos maar probeer het niet te laten merken-gezicht.",m:1,p:2},
{cat:"missie",tier:"genart",t:"Vertel het meest awkward familiediner-moment dat je hebt meegemaakt.",m:2,p:4},
{cat:"missie",tier:"genart",t:"Doe alsof je net een Oscar hebt gewonnen. Geef een dankwoord.",m:1,p:3},
{cat:"missie",tier:"genart",t:"Doe je ik snap de les niet maar doe alsof-gezicht.",m:1,p:2},
{cat:"missie",tier:"genart",t:"Vertel iets dat je stiekem doet waarvan je weet dat het raar is.",m:2,p:4},
{cat:"missie",tier:"genart",t:"Doe alsof je niest maar maak het zo dramatisch mogelijk.",m:1,p:2},
{cat:"missie",tier:"genart",t:"Ga staan en doe de awkward prom photo-pose met een speler naar keuze.",m:2,p:3},
{cat:"missie",tier:"genart",t:"Vertel je raarste nachtmerrie. In detail.",m:1,p:3},
{cat:"missie",tier:"genart",t:"Doe je oh nee ik heb het verkeerde bericht gestuurd-reactie na.",m:1,p:2},
{cat:"missie",tier:"genart",t:"Vertel eerlijk: hoeveel keer check je jezelf in de spiegel per dag?",m:1,p:2},
{cat:"wie",tier:"party",t:"Wie zou als eerste worden opgepakt op vakantie?"},
{cat:"wie",tier:"party",t:"Wie zou het snelst ontslagen worden?"},
{cat:"wie",tier:"party",t:"Wie wordt als eerste miljonair?"},
{cat:"wie",tier:"party",t:"Wie verdwaalt het snelst in een vreemde stad?"},
{cat:"wie",tier:"party",t:"Wie geeft het meeste geld uit deze vakantie?"},
{cat:"wie",tier:"party",t:"Wie valt vanavond als eerste in slaap?"},
{cat:"wie",tier:"party",t:"Wie kan het beste een geheim bewaren?"},
{cat:"wie",tier:"party",t:"Wie zou de groep leiden op een onbewoond eiland?"},
{cat:"wie",tier:"party",t:"Wie liegt het overtuigendst?"},
{cat:"wie",tier:"party",t:"Wie zou de rekening ontvluchten?"},
{cat:"wie",tier:"party",t:"Wie kletst zich overal uit?"},
{cat:"wie",tier:"party",t:"Wie is stiekem het meest competitief?"},
{cat:"wie",tier:"party",t:"Wie vergeet morgen het meeste van vanavond?"},
{cat:"wie",tier:"party",t:"Wie zou viral gaan op social media?"},
{cat:"wie",tier:"party",t:"Wie zou het eerste trouwen?"},
{cat:"wie",tier:"party",t:"Wie zou de slechtste Uber-chauffeur zijn?"},
{cat:"wie",tier:"party",t:"Wie zou het langst overleven op een onbewoond eiland?"},
{cat:"wie",tier:"party",t:"Wie is het luidruchtigst als hij dronken is?"},
{cat:"wie",tier:"party",t:"Wie zou de beste barman zijn?"},
{cat:"wie",tier:"party",t:"Wie heeft de meeste geluk op vakantie?"},
{cat:"wie",tier:"party",t:"Wie is stiekem het slimst van de groep?"},
{cat:"wie",tier:"party",t:"Wie zou als eerste een tattoo nemen op vakantie?"},
{cat:"wie",tier:"party",t:"Wie is de slechtste verliezer?"},
{cat:"wie",tier:"party",t:"Wie zou als eerste ruzie maken met een ober?"},
{cat:"wie",tier:"party",t:"Wie stuurt de langste berichten in de groepschat?"},
{cat:"wie",tier:"party",t:"Wie zou de beste stand-up comedian zijn?"},
{cat:"wie",tier:"party",t:"Wie is altijd te laat?"},
{cat:"wie",tier:"party",t:"Wie kent de meeste random feiten?"},
{cat:"wie",tier:"party",t:"Wie is de ergste backseat driver?"},
{cat:"wie",tier:"party",t:"Wie zou als eerste een scooter crashen op vakantie?"},
{cat:"wie",tier:"flirty",t:"Wie wordt verliefd tijdens deze trip?"},
{cat:"wie",tier:"flirty",t:"Wie is stiekem de beste flirter?"},
{cat:"wie",tier:"flirty",t:"Wie heeft de meeste crushes gehad dit jaar?"},
{cat:"wie",tier:"flirty",t:"Wie zou de meeste matches krijgen op Tinder?"},
{cat:"wie",tier:"flirty",t:"Wie is stiekem een hopeloos romanticus?"},
{cat:"wie",tier:"flirty",t:"Wie is de beste kisser van de groep?"},
{cat:"wie",tier:"flirty",t:"Wie zou het snelst een vakantieliefde krijgen?"},
{cat:"wie",tier:"flirty",t:"Wie heeft het drukste liefdesleven?"},
{cat:"wie",tier:"flirty",t:"Wie wordt het roodst als hij een compliment krijgt?"},
{cat:"wie",tier:"flirty",t:"Wie zou een reality-datingshow winnen?"},
{cat:"wie",tier:"flirty",t:"Wie heeft het vaakst een relatie gehad?"},
{cat:"wie",tier:"flirty",t:"Wie is de perfecte schoonzoon?"},
{cat:"wie",tier:"flirty",t:"Wie ghostt het vaakst?"},
{cat:"wie",tier:"flirty",t:"Wie heeft de beste opening lines?"},
{cat:"wie",tier:"flirty",t:"Wie is het meest ongemakkelijk op een eerste date?"},
{cat:"wie",tier:"extreme",t:"Wie zou het snelst in de gevangenis belanden?"},
{cat:"wie",tier:"extreme",t:"Wie zou het langst overleven in een zombie-apocalyps?"},
{cat:"wie",tier:"extreme",t:"Wie zou als eerste naakt rondrennen op een dare?"},
{cat:"wie",tier:"extreme",t:"Wie heeft de meest illegale dingen gedaan?"},
{cat:"wie",tier:"extreme",t:"Wie is het gevaarlijkst achter het stuur?"},
{cat:"wie",tier:"extreme",t:"Wie zou zijn telefoon het snelst afgeven voor een raid?"},
{cat:"wie",tier:"extreme",t:"Wie durft het meest op vakantie?"},
{cat:"wie",tier:"extreme",t:"Wie zou als eerste van een klif springen?"},
{cat:"wie",tier:"extreme",t:"Wie zou als eerste meedoen aan een vechtpartij?"},
{cat:"wie",tier:"extreme",t:"Wie heeft de minste angst?"},
{cat:"wie",tier:"extreme",t:"Wie is het meest roekeloos met geld?"},
{cat:"wie",tier:"extreme",t:"Wie zou overleven als gladiator?"},
{cat:"wie",tier:"extreme",t:"Wie zou als undercover-agent het snelst betrapt worden?"},
{cat:"wie",tier:"extreme",t:"Wie zou een bank beroven en ermee wegkomen?"},
{cat:"wie",tier:"extreme",t:"Wie is het gevaarlijkst als hij boos is?"},
{cat:"wie",tier:"genart",t:"Wie heeft de meest genante zoekgeschiedenis?"},
{cat:"wie",tier:"genart",t:"Wie klaagt het meest over kleine dingen?"},
{cat:"wie",tier:"genart",t:"Wie is stiekem de meest dramatische?"},
{cat:"wie",tier:"genart",t:"Wie heeft de lelijkste schoen-collectie?"},
{cat:"wie",tier:"genart",t:"Wie maakt de meeste typefouten?"},
{cat:"wie",tier:"genart",t:"Wie is het minst zelfredzaam?"},
{cat:"wie",tier:"genart",t:"Wie zou het snelst huilen bij een film?"},
{cat:"wie",tier:"genart",t:"Wie is de grootste mama kindje?"},
{cat:"wie",tier:"genart",t:"Wie liegt het slechtst?"},
{cat:"wie",tier:"genart",t:"Wie is het meest vergeetachtig?"},
{cat:"wie",tier:"genart",t:"Wie heeft de raarste eetgewoonten?"},
{cat:"wie",tier:"genart",t:"Wie is het luidruchtigst in zijn slaap?"},
{cat:"wie",tier:"genart",t:"Wie is stiekem het onzekerst?"},
{cat:"wie",tier:"genart",t:"Wie zou het slechtst alleen kunnen wonen?"},
{cat:"wie",tier:"genart",t:"Wie heeft de meest genante guilty pleasure?"},
{cat:"wie",tier:"spicy",t:"Wie is het wildst in bed?"},
{cat:"wie",tier:"spicy",t:"Wie stuurt de meeste dronken berichten naar hun ex?"},
{cat:"wie",tier:"spicy",t:"Wie heeft de hoogste body count?"},
{cat:"wie",tier:"spicy",t:"Wie is stiekem het kinkiest?"},
{cat:"wie",tier:"spicy",t:"Wie heeft de beste seks-verhalen?"},
{cat:"wie",tier:"spicy",t:"Wie zou het snelst een OnlyFans starten?"},
{cat:"wie",tier:"spicy",t:"Wie is het luidruchtigst tijdens seks?"},
{cat:"wie",tier:"spicy",t:"Wie heeft de meeste one-night-stands gehad?"},
{cat:"wie",tier:"spicy",t:"Wie zou het snelst naakt zwemmen?"},
{cat:"wie",tier:"spicy",t:"Wie heeft het meest geexperimenteerd?"},
{cat:"wie",tier:"spicy",t:"Wie is de beste dirty talker?"},
{cat:"wie",tier:"spicy",t:"Wie zou een seksscene het best acteren?"},
{cat:"wie",tier:"spicy",t:"Wie is het meest ervaren van de groep?"},
{cat:"wie",tier:"spicy",t:"Wie heeft het langst drooggestaan?"},
{cat:"wie",tier:"spicy",t:"Wie is stiekem de meest romantische in bed?"},
{cat:"koning",tier:"party",t:"Doe je beste imitatie van de koning, 15 seconden.",m:1,p:2},
{cat:"koning",tier:"party",t:"Dans 15 seconden alsof je alleen thuis bent.",m:1,p:2},
{cat:"koning",tier:"party",t:"Doe het geluid van een dier naar keuze van de koning, 10 sec.",m:1,p:2},
{cat:"koning",tier:"party",t:"Doe 30 push-ups of drink 5 slokken. Halverwege stoppen = drink 3.",m:2,p:4},
{cat:"koning",tier:"party",t:"De koning kiest: jij rapt 15 sec over een onderwerp dat hij kiest.",m:2,p:3},
{cat:"koning",tier:"party",t:"De koning beslist wie er nu 3 drinkt. Geen excuses.",m:1,p:2},
{cat:"koning",tier:"party",t:"Sta op en dans alsof je in een muziekvideo zit. De koning beoordeelt.",m:2,p:3},
{cat:"koning",tier:"party",t:"De koning kiest een accent dat je de komende ronde spreekt.",m:2,p:3},
{cat:"koning",tier:"party",t:"Je moet de koning aanspreken met Uwe Majesteit of drink 1 per keer dat je het vergeet.",m:1,p:2},
{cat:"koning",tier:"party",t:"De koning kiest 2 spelers: zij moeten een sketch opvoeren in 30 sec.",m:2,p:3},
{cat:"koning",tier:"party",t:"Ga naar een andere tafel en vertel dat je een boodschap van de koning hebt.",m:2,p:3},
{cat:"koning",tier:"party",t:"De koning mag een speler een regel opleggen voor de komende 5 minuten.",m:2,p:3},
{cat:"koning",tier:"party",t:"Doe alsof je de bodyguard van de koning bent. Bescherm hem 1 minuut.",m:1,p:2},
{cat:"koning",tier:"party",t:"De koning kiest: wie zingt het refrein van een nummer naar zijn keuze?",m:2,p:3},
{cat:"koning",tier:"party",t:"Sta op en applaudisseer 15 sec voor de koning alsof hij een toespraak heeft gegeven.",m:1,p:2},
{cat:"koning",tier:"party",t:"De koning geeft je een woord. Jij maakt er een liedje van in 15 sec.",m:2,p:3},
{cat:"koning",tier:"party",t:"De koning kiest: iedereen moet 1 ding zeggen dat ze bewonderen aan de koning.",m:1,p:2},
{cat:"koning",tier:"party",t:"Maak een kroon van servetten voor de koning. Je hebt 30 sec.",m:1,p:2},
{cat:"koning",tier:"party",t:"De koning beslist: jij bestelt het volgende rondje.",m:2,p:3},
{cat:"koning",tier:"party",t:"De koning kiest: jij moet een compliment geven aan een vreemde namens de koning.",m:2,p:3},
{cat:"koning",tier:"party",t:"Ga staan en kondig de koning aan alsof hij een stadion binnenloopt.",m:1,p:2},
{cat:"koning",tier:"party",t:"De koning kiest: doe 30 sec een imitatie van een speler naar keuze van de koning.",m:2,p:3},
{cat:"koning",tier:"party",t:"De koning mag een wet instellen die geldt tot de volgende ronde.",m:2,p:3},
{cat:"koning",tier:"party",t:"De koning kiest 2 spelers: arm-wrestle. Verliezer drinkt 3.",m:1,p:3},
{cat:"koning",tier:"party",t:"Vertel de koning een grap. Lacht hij niet? Drink 3.",m:2,p:3},
{cat:"koning",tier:"flirty",t:"Doe je beste sexy danspasje voor de groep, 15 sec lang.",m:2,p:4},
{cat:"koning",tier:"flirty",t:"Ga naar een vreemde en vraag of je er goed uitziet. Kom terug met het antwoord.",m:2,p:3},
{cat:"koning",tier:"flirty",t:"De koning kiest: geef een speler een knuffel van 10 sec.",m:2,p:3},
{cat:"koning",tier:"flirty",t:"De koning kiest: wie moet wie een compliment geven? Moet oprecht zijn.",m:1,p:2},
{cat:"koning",tier:"flirty",t:"Doe alsof de koning je crush is. Flirt 15 sec. De groep beoordeelt.",m:2,p:4},
{cat:"koning",tier:"flirty",t:"De koning kiest: stuur een flirterig bericht naar iemand die de koning aanwijst.",m:3,p:5},
{cat:"koning",tier:"flirty",t:"De koning kiest: wie moet wie op de wang zoenen?",m:2,p:3},
{cat:"koning",tier:"flirty",t:"Fluister iets liefs in het oor van de speler die de koning aanwijst.",m:2,p:3},
{cat:"koning",tier:"flirty",t:"De koning kiest: doe je verleidelijkste loop naar de bar en terug.",m:2,p:3},
{cat:"koning",tier:"flirty",t:"De koning kiest: wie moet er Ik vind je leuk zeggen tegen een vreemde?",m:2,p:4},
{cat:"koning",tier:"flirty",t:"De koning kiest: beschrijf de speler links als je droompartner.",m:1,p:2},
{cat:"koning",tier:"flirty",t:"De koning kiest: doe een slow-dance met een speler naar keuze. 10 sec.",m:2,p:4},
{cat:"koning",tier:"flirty",t:"Vertel de koning wat je het aantrekkelijkst vindt aan hem. Of drink 3.",m:2,p:3},
{cat:"koning",tier:"flirty",t:"De koning kiest: stuur een hartje naar het 5e contact in je telefoon.",m:2,p:3},
{cat:"koning",tier:"flirty",t:"De koning kiest: knipoog naar 3 vreemden achter elkaar.",m:2,p:3},
{cat:"koning",tier:"extreme",t:"Laat je hele belgeschiedenis zien aan de groep.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"Stuur ik denk aan je naar het laatst ge-DM-de contact. Screenshot.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"Laat de groep 30 sec door je Instagram-volgers scrollen.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"Bel je moeder en vertel dat je verloofd bent. Hang na 10 sec op.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"Geef je telefoon 2 min aan de koning. Die mag 1 bericht sturen.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"Laat je zoekgeschiedenis van vandaag zien of drink 5.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"Stuur een spraakbericht naar je crush of ex: Ik moest even aan je denken.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"Laat de groep een bericht typen in een groepschat naar keuze.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"De koning kiest: laat de inhoud van je portemonnee zien.",m:2,p:3},
{cat:"koning",tier:"extreme",t:"De koning kiest: bel iemand en doe alsof je diegene uitnodigt voor je bruiloft.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"De koning kiest: stuur een voice note van 10 sec naar een contact die hij kiest.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"De koning laat je een bericht sturen naar je ex. Hij typt het.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"De koning kiest: laat je laatst verwijderde foto zien.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"De koning kiest: bel iemand en zeg alleen Drieentwintig. Hang op.",m:2,p:3},
{cat:"koning",tier:"extreme",t:"De koning kiest: lees je laatste WhatsApp-gesprek hardop voor. Eerste 5 berichten.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"De koning kiest: stuur Ben je wakker? naar het 7e contact.",m:2,p:3},
{cat:"koning",tier:"extreme",t:"De koning kiest: post een foto die hij maakt als story. Nu.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"De koning kiest: bel een pizzeria en bestel iets dat niet op het menu staat.",m:2,p:3},
{cat:"koning",tier:"extreme",t:"De koning kiest: laat je Spotify on repeat zien.",m:2,p:3},
{cat:"koning",tier:"extreme",t:"De koning kiest: stuur Ik weet je geheim naar iemand. Geen context.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"Laat de koning 1 minuut je Instagram beheren. Alles mag.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"De koning kiest: bel een contact en doe 20 sec alsof je in een film zit.",m:2,p:3},
{cat:"koning",tier:"extreme",t:"De koning kiest: deel het aantal ongelezen berichten in je inbox.",m:2,p:3},
{cat:"koning",tier:"extreme",t:"De koning kiest: wissel je profielfoto voor een die hij maakt. Minimaal 1 uur.",m:3,p:5},
{cat:"koning",tier:"extreme",t:"De koning kiest: lees je bio voor en de groep herschrijft het.",m:2,p:3},
{cat:"koning",tier:"genart",t:"Vertel het genantste dat je deze vakantie hebt gedaan.",m:2,p:3},
{cat:"koning",tier:"genart",t:"Vertel je meest awkward date-verhaal.",m:2,p:3},
{cat:"koning",tier:"genart",t:"Vertel je meest illegale actie ooit. De groep oordeelt.",m:2,p:4},
{cat:"koning",tier:"genart",t:"De koning kiest: doe een imitatie van hoe je eruitziet als je flirt.",m:2,p:3},
{cat:"koning",tier:"genart",t:"De koning kiest: vertel je meest genante schoolverhaal.",m:2,p:3},
{cat:"koning",tier:"genart",t:"De koning kiest: doe alsof je slaapwandelt door het terras.",m:2,p:3},
{cat:"koning",tier:"genart",t:"De koning kiest: vertel het domste bericht dat je ooit hebt gestuurd.",m:2,p:3},
{cat:"koning",tier:"genart",t:"De koning kiest: doe je ik word betrapt-gezicht.",m:1,p:2},
{cat:"koning",tier:"genart",t:"De koning kiest: vertel wanneer je voor het laatst hebt afgegaan.",m:2,p:3},
{cat:"koning",tier:"genart",t:"De koning kiest: doe een imitatie van jezelf als je dronken bent.",m:2,p:3},
{cat:"koning",tier:"social",t:"Eet of drink iets dat de groep voor je mixt.",m:3,p:5},
{cat:"koning",tier:"social",t:"De koning kiest: tag 3 random mensen in je story.",m:3,p:5},
{cat:"koning",tier:"social",t:"De koning kiest: laat je screen time per app zien.",m:2,p:3},
{cat:"koning",tier:"social",t:"De koning kiest: reageer met een hartje op de story van een ex.",m:3,p:5},
{cat:"koning",tier:"social",t:"De koning kiest: post een poll Rate mijn vakantie 1-10.",m:2,p:3},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit ik ben onderweg gestuurd terwijl ik nog thuis was."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit van iemand anders drankje gedronken zonder te vragen."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit gedaan alsof ik sliep om een gesprek te vermijden."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit gehuild van een film in het bijzijn van anderen."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit op de verkeerde persoon gereageerd in een groepschat."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit iemands eten gestolen uit de koelkast."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit een weddenschap verloren en de straf niet uitgevoerd."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit over mijn leeftijd gelogen om ergens binnen te komen."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit in zee gezwommen na middernacht."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit een heel seizoen in 1 dag gebingewatcht."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit een excuus verzonnen om een feest te skippen."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit met mijn eten gespeeld als volwassene."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit gedaan alsof ik belde om een situatie te ontsnappen."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit tegen mijn ouders gelogen over waar ik was."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit een heel drankje in 1 teug gedronken op een dare."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit iemand anders de schuld gegeven voor mijn scheet."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit in een fontein gezwommen."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit een vlucht of trein gemist door mijn eigen schuld."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit een geheim bewaard dat ik had moeten vertellen."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit een bijnaam gehad die ik haatte."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit dronken eten besteld en het de volgende ochtend vergeten."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit in het openbaar mijn broek gescheurd."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit een hele dag in pyjama doorgebracht."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit iemand per ongeluk met de verkeerde naam aangesproken."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit een drankje over mezelf gemorst in het openbaar."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit een selfie genomen op het toilet."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit een heel gesprek gevoerd met iemand die ik niet kende, denkend dat ik ze kende."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit achter iemands rug om over ze gepraat."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit een kater gehad die langer dan 24 uur duurde."},
{cat:"nhie",tier:"party",t:"Ik heb nog nooit op vakantie iets gestolen uit het hotel."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit iemand gekust die ik net had ontmoet."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit een ex terug-ge-DMd na middernacht."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit een date geghost."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit iemand uit deze groep aantrekkelijk gevonden."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit twee mensen tegelijk ge-date."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit een crush gehad op een vriend van een vriend."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit iemand gedatet die ik online heb ontmoet."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit iemand gekust puur om een dare."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit per ongeluk tegen iemand aangelopen om een gesprek te starten."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit verliefd geweest op iemand die het niet wist."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit een love letter geschreven en het niet verstuurd."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit iemand ge-date alleen voor het gratis eten."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit een telefoonnummer gevraagd en het nooit gebeld."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit iemand gedumpt via een bericht."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit gejaloersd op de ex van mijn partner."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit een situationship gehad."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit een pickup line gebruikt in het echt."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit iemand gekust op een eerste date."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit gedaan alsof ik iemand leuk vond om geen nee te hoeven zeggen."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit gestalkt wie mijn ex nu datet."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit een vakantieliefde gehad."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit een goedmorgentekst gestuurd naar iemand die ik net kende."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit verliefd geweest op 2 mensen tegelijk."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit gefaked dat ik iemand leuk vond voor de aandacht."},
{cat:"nhie",tier:"flirty",t:"Ik heb nog nooit een relatie gehad die korter duurde dan een week."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit iets gestolen uit een winkel."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit gevochten in een club of bar."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit de politie moeten bellen."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit een tattoo of piercing genomen onder invloed."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit een voertuig bestuurd terwijl ik dat niet mocht."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit illegaal ergens ingebroken."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit iets verborgen voor de politie."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit een overheidsregel bewust overtreden."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit wiet gerookt in een land waar het illegaal is."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit een weddenschap gedaan die ik 100 procent kon verliezen."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit van een brug of klif gesprongen."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit een nacht doorgehaald en de volgende dag naar werk gegaan."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit een voertuig beschadigd en het niet gemeld."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit een bouncer omgepraat."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit iets verzonnen op mijn CV."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit een nooduitgang gebruikt terwijl er geen nood was."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit een nep-ID gebruikt."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit dronken online iets gekocht dat ik niet nodig had."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit wakker geworden op een plek zonder te weten hoe ik er kwam."},
{cat:"nhie",tier:"extreme",t:"Ik heb nog nooit iemands eigendom per ongeluk kapotgemaakt en het verzwegen."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit een dronken spraakbericht gestuurd dat ik de volgende ochtend betreurde."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit in mijn broek geplast als volwassene."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit in een Uber of taxi gekotst."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit een genante beltoon laten afgaan in het openbaar."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit gehuild in het openbaar om iets stoms."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit een bericht gestuurd naar de verkeerde chat."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit iets stoms gezegd in een sollicitatiegesprek."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit mijn eigen naam verkeerd gespeld."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit geluid gemaakt op het toilet terwijl iemand luisterde."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit een deur geduwd terwijl er trek stond, meerdere keren."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit tegen een glazen deur gelopen."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit per ongeluk hardop gepraat tegen mezelf waar anderen bij waren."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit iemand uitgelachen en toen hetzelfde overkwam."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit een bericht van 2 regels geschreven dat ik 30 min heb herschreven."},
{cat:"nhie",tier:"genart",t:"Ik heb nog nooit dronken tegen een lantaarnpaal gelopen."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit iemand geblokkeerd op social media en later weer ontblokt."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit een screenshot gemaakt van een privegesprek en doorgestuurd."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit iemand gestalkt op social media voor een date."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit per ongeluk een oude foto geliked terwijl ik stalkte."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit een nep-account aangemaakt."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit iemand ontvolgd en weer gevolgd zodat ze het niet merkten."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit een bericht verwijderd nadat ik het had gestuurd hopend dat niemand het zag."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit mijn locatie gedeeld en vergeten dat het aanstond."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit een foto bewerkt tot het niet meer op me leek."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit een catfish-achtig profiel gebruikt op een datingapp."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit iemands wachtwoord geraden om in hun account te kijken."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit een story gepost en hem binnen 5 min verwijderd."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit mijn ex nieuwe partner gestalkt."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit dronken een comment geplaatst die ik de volgende dag verwijderde."},
{cat:"nhie",tier:"social",t:"Ik heb nog nooit gedaan alsof ik een DM niet had gezien terwijl ik het wel had gelezen."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit een naaktfoto gestuurd."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit seks gehad op een plek waar je gepakt kon worden."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit naakt gezwommen."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit iemands telefoon doorgescrold zonder toestemming."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit seks gehad op een eerste date."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit een one-night-stand gehad op vakantie."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit iets in bed geprobeerd dat ik van het internet had."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit seks gehad terwijl iemand in dezelfde kamer sliep."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit iemand teruggenomen puur voor de seks."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit een seks-toy gekocht."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit dirty talk geprobeerd en gefaald."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit een naaktfoto ontvangen die ik niet verwachtte."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit gefantaseerd over iemand in deze groep."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit seks gehad in een auto."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit iemand ge-date die ouder was dan 5 jaar verschil."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit seks gehad terwijl ik eigenlijk te dronken was."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit een booty call gestuurd na middernacht."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit gelogen over mijn body count."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit iemand gekust alleen omdat ik verveeld was."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit seks gehad op het strand."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit een keer gehad dat ik halverwege wilde stoppen."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit gefaked."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit een threesome-voorstel gehad."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit naakt door het huis van iemand anders gelopen."},
{cat:"nhie",tier:"spicy",t:"Ik heb nog nooit iemand ge-date alleen vanwege hun uiterlijk."},
{cat:"ba",tier:"party",t:"Wat zou er op je grafsteen staan als je vrienden het mochten kiezen?"},
{cat:"ba",tier:"party",t:"Schrijf een excuus-bericht aan je baas waarom je niet komt werken."},
{cat:"ba",tier:"party",t:"Wat zou je roepen als je achterna werd gezeten door een beer?"},
{cat:"ba",tier:"party",t:"Wat is het ergste cadeau dat je kunt geven aan je schoonmoeder?"},
{cat:"ba",tier:"party",t:"Wat zou je doen met 1 miljoen als je het binnen 1 uur moet uitgeven?"},
{cat:"ba",tier:"party",t:"Schrijf een review van je eigen leven op Google Maps."},
{cat:"ba",tier:"party",t:"Vertel een leugen over jezelf die zo gek is dat niemand het gelooft."},
{cat:"ba",tier:"party",t:"Als je 1 wet mocht breken zonder gevolgen, welke?"},
{cat:"ba",tier:"party",t:"Beschrijf je ergste kater ooit in 1 zin."},
{cat:"ba",tier:"party",t:"Wat is het domste dat je zou kopen als je plotseling miljonair werd?"},
{cat:"ba",tier:"party",t:"Beschrijf deze vakantie als filmtitel."},
{cat:"ba",tier:"party",t:"Wat zou je superheldennaam zijn en wat is je kracht?"},
{cat:"ba",tier:"party",t:"Wat staat er op je nep-visitekaartje als je doet alsof je iemand anders bent?"},
{cat:"ba",tier:"party",t:"Beschrijf je slaapgewoonten als hotelreview."},
{cat:"ba",tier:"party",t:"Als je 1 dag president was, wat zou je als eerste veranderen?"},
{cat:"ba",tier:"party",t:"Wat zou het slechtstmogelijke tattoo zijn om te nemen vanavond?"},
{cat:"ba",tier:"party",t:"Bedenk een naam voor een cocktail gebaseerd op je persoonlijkheid."},
{cat:"ba",tier:"party",t:"Als je 1 speler mocht klonen, wie en waarom?"},
{cat:"ba",tier:"party",t:"Beschrijf je ochtend-routine als een horrorfilm."},
{cat:"ba",tier:"party",t:"Als het leven een game was, wat is dan jouw achievement dat je hebt vrijgespeeld?"},
{cat:"ba",tier:"party",t:"Wat is het slechtste advies dat je ooit hebt opgevolgd?"},
{cat:"ba",tier:"party",t:"Verzin een advertentie voor jezelf als huisgenoot."},
{cat:"ba",tier:"party",t:"Beschrijf je kookskills in 1 eerlijke zin."},
{cat:"ba",tier:"party",t:"Wat zou je laatste maaltijd zijn als je mocht kiezen?"},
{cat:"ba",tier:"party",t:"Bedenk de slechtste naam voor een restaurant."},
{cat:"ba",tier:"party",t:"Als je moest overleven met alleen wat in je zakken zit, hoe lang hou je het vol?"},
{cat:"ba",tier:"party",t:"Beschrijf het ergste restaurant-bezoek dat je kunt bedenken."},
{cat:"ba",tier:"party",t:"Als je een land mocht stichten, hoe zou het heten en wat is wet nummer 1?"},
{cat:"ba",tier:"party",t:"Wat is het meest nutteloze talent dat je hebt?"},
{cat:"ba",tier:"party",t:"Verzin de langste excuus-zin waarom je te laat bent."},
{cat:"ba",tier:"flirty",t:"Wat is het ergste dat je kunt zeggen op een eerste date?"},
{cat:"ba",tier:"flirty",t:"Beschrijf jezelf als Tinder-bio in 1 zin."},
{cat:"ba",tier:"flirty",t:"Wat zou je ex over je zeggen in 1 zin?"},
{cat:"ba",tier:"flirty",t:"Wat is de ergste pickup line die je kunt verzinnen?"},
{cat:"ba",tier:"flirty",t:"Schrijf een dramatisch breakup-bericht voor een relatie van 2 dagen."},
{cat:"ba",tier:"flirty",t:"Hoe zou je een date uitleggen aan een alien?"},
{cat:"ba",tier:"flirty",t:"Beschrijf je ideale partner maar het klinkt als een sollicitatie."},
{cat:"ba",tier:"flirty",t:"Wat is de ergste reden om iemand te dumpen?"},
{cat:"ba",tier:"flirty",t:"Schrijf een Tinder-bio voor de speler links van je."},
{cat:"ba",tier:"flirty",t:"Wat zou je zeggen als je per ongeluk ik hou van je zei op een 2e date?"},
{cat:"ba",tier:"flirty",t:"Beschrijf je slechtste date ooit als filmrecensie."},
{cat:"ba",tier:"flirty",t:"Wat is het creepyste compliment dat je kunt geven?"},
{cat:"ba",tier:"flirty",t:"Hoe zou je flirten als je alleen emojis mocht gebruiken? Doe voor."},
{cat:"ba",tier:"flirty",t:"Beschrijf de perfecte Valentijnsdag maar maak het zo over-the-top mogelijk."},
{cat:"ba",tier:"flirty",t:"Wat is het meest romantische dat je ooit hebt gedaan?"},
{cat:"ba",tier:"flirty",t:"Schrijf een sorry ik heb je geghost-bericht."},
{cat:"ba",tier:"flirty",t:"Beschrijf je ideale huwelijksaanzoek in 10 woorden."},
{cat:"ba",tier:"flirty",t:"Wat is het raarste dat je aantrekkelijk vindt?"},
{cat:"ba",tier:"flirty",t:"Hoe zou je breken met iemand als je het op zijn vriendelijkst moest doen?"},
{cat:"ba",tier:"flirty",t:"Verzin de meest overdreven openingszin voor een datingapp."},
{cat:"ba",tier:"extreme",t:"Als je 24 uur onzichtbaar was, wat zou je doen?"},
{cat:"ba",tier:"extreme",t:"Welk geheim zou je nooit aan je ouders vertellen?"},
{cat:"ba",tier:"extreme",t:"Wat is het ergste dat je zou doen voor 10.000 euro?"},
{cat:"ba",tier:"extreme",t:"Als je moest kiezen: nooit meer liegen of nooit meer de waarheid vertellen?"},
{cat:"ba",tier:"extreme",t:"Wat is het illegalste dat je ooit serieus hebt overwogen?"},
{cat:"ba",tier:"extreme",t:"Als je 1 persoon mocht wipen uit je geheugen, wie?"},
{cat:"ba",tier:"extreme",t:"Wat is het engste dat je hebt meegemaakt?"},
{cat:"ba",tier:"extreme",t:"Als je 1 dag ongestraft alles mocht doen, wat zou je doen?"},
{cat:"ba",tier:"extreme",t:"Welk geheim van iemand anders weet je dat je nooit had mogen weten?"},
{cat:"ba",tier:"extreme",t:"Wat zou je doen als je wakker werd in een ander land zonder telefoon of geld?"},
{cat:"ba",tier:"extreme",t:"Als je je eigen dood moest faken, hoe zou je het aanpakken?"},
{cat:"ba",tier:"extreme",t:"Wat is het ergste dat je hebt gedaan en er mee bent weggekomen?"},
{cat:"ba",tier:"extreme",t:"Als je 1 misdaad mocht plegen zonder gevolgen, welke?"},
{cat:"ba",tier:"extreme",t:"Wat is het gevaarlijkste dat je ooit hebt gedaan?"},
{cat:"ba",tier:"extreme",t:"Beschrijf hoe je een bankoverval zou plannen theoretisch."},
{cat:"ba",tier:"genart",t:"Wat is je guilty pleasure waar je je echt voor schaamt?"},
{cat:"ba",tier:"genart",t:"Wat is de meest sus zin in je zoekgeschiedenis?"},
{cat:"ba",tier:"genart",t:"Wat is het domste dat je ooit hebt gegoogeld?"},
{cat:"ba",tier:"genart",t:"Beschrijf je meest genante puberteitsverhaal."},
{cat:"ba",tier:"genart",t:"Wat is iets dat je doet als niemand kijkt?"},
{cat:"ba",tier:"genart",t:"Wat is het meest awkward dat je ouders over je hebben ontdekt?"},
{cat:"ba",tier:"genart",t:"Beschrijf je slechtste outfit ooit."},
{cat:"ba",tier:"genart",t:"Wat is het raarste dat je doet als je alleen thuis bent?"},
{cat:"ba",tier:"genart",t:"Vertel het slechtstmogelijke excuus voor een scheet in het openbaar."},
{cat:"ba",tier:"genart",t:"Beschrijf je meest cringe fase als tiener."},
{cat:"ba",tier:"genart",t:"Wat is iets dat je doet dat je vriendengroep raar zou vinden?"},
{cat:"ba",tier:"genart",t:"Wat is het genantste liedje op je Spotify?"},
{cat:"ba",tier:"genart",t:"Beschrijf je ik dacht dat niemand keek-moment."},
{cat:"ba",tier:"genart",t:"Wat is het domste dat je ooit hebt gekocht?"},
{cat:"ba",tier:"genart",t:"Beschrijf je slechtste hairstyle ooit."},
{cat:"ba",tier:"social",t:"Schrijf een DM naar je crush die je nooit zou durven sturen."},
{cat:"ba",tier:"social",t:"Bedenk de meest cringe Instagram-caption."},
{cat:"ba",tier:"social",t:"Schrijf een breakup-bericht als Instagram-comment."},
{cat:"ba",tier:"social",t:"Beschrijf je leven als een TikTok-trend."},
{cat:"ba",tier:"social",t:"Wat zou je posten als je wist dat alleen 1 persoon het zou zien?"},
{cat:"ba",tier:"social",t:"Schrijf een LinkedIn-post over deze avond alsof het zakelijk is."},
{cat:"ba",tier:"social",t:"Bedenk de slechtste Tinder-bio voor een speler naar keuze."},
{cat:"ba",tier:"social",t:"Wat zou je story zijn als je geen schaamte had?"},
{cat:"ba",tier:"social",t:"Schrijf een review van jezelf als Airbnb-gast."},
{cat:"ba",tier:"social",t:"Beschrijf deze groep als reality-TV show. Wat is de titel?"},
{cat:"ba",tier:"spicy",t:"Beschrijf je ideale vrijdagavond als niemand het zou weten."},
{cat:"ba",tier:"spicy",t:"Wat is de meest awkward seks-vraag die je kunt stellen aan een date?"},
{cat:"ba",tier:"spicy",t:"Beschrijf je slechtste seks ooit als filmrecensie."},
{cat:"ba",tier:"spicy",t:"Wat is het raarste dat je ooit in bed hebt meegemaakt?"},
{cat:"ba",tier:"spicy",t:"Verzin de slechtst mogelijke dirty talk-zin."},
{cat:"ba",tier:"spicy",t:"Beschrijf je type maar maak het zo specifiek dat het verdacht wordt."},
{cat:"ba",tier:"spicy",t:"Wat is het meest NSFW dat je ooit op je werktelefoon hebt gehad?"},
{cat:"ba",tier:"spicy",t:"Schrijf een eerlijke review van je eigen seks-skills."},
{cat:"ba",tier:"spicy",t:"Beschrijf je walk of shame als motivational speech."},
{cat:"ba",tier:"spicy",t:"Wat is het ergste dat je zou toegeven onder truth or dare?"},
{cat:"versus",tier:"party",t:"Staarwedstrijd: eerste die lacht drinkt 3.",m:1,p:3},
{cat:"versus",tier:"party",t:"Wie kan het langst een ijsblokje in zijn mond houden?",m:2,p:4},
{cat:"versus",tier:"party",t:"Rap battle: 15 sec elk over een onderwerp dat de groep kiest.",m:2,p:4},
{cat:"versus",tier:"party",t:"Wie kan de langste boer laten?",m:1,p:3},
{cat:"versus",tier:"party",t:"Arm-wrestle. Verliezer drinkt 3.",m:1,p:3},
{cat:"versus",tier:"party",t:"Wie kan het snelst een biertje drinken?",m:2,p:4},
{cat:"versus",tier:"party",t:"Wie kent meer songteksten? De groep kiest een nummer.",m:2,p:4},
{cat:"versus",tier:"party",t:"Thumb war. Best of 3. Verliezer drinkt.",m:1,p:3},
{cat:"versus",tier:"party",t:"Wie kan het langst op 1 been staan met ogen dicht?",m:1,p:3},
{cat:"versus",tier:"party",t:"Wie kan de beste slechte imitatie van de ander doen? Groep stemt.",m:2,p:4},
{cat:"versus",tier:"party",t:"Steen-papier-schaar: best of 5. Verliezer drinkt 3, winnaar deelt 3 uit.",m:1,p:4},
{cat:"versus",tier:"party",t:"Wie kan het meeste water in 1 teug drinken?",m:1,p:3},
{cat:"versus",tier:"party",t:"Wie bedenkt de betere belediging over de ander? Groep stemt.",m:2,p:4},
{cat:"versus",tier:"party",t:"Wie kan het langst een rechte lijn lopen met ogen dicht?",m:1,p:3},
{cat:"versus",tier:"party",t:"Wie kent meer vlaggen? De groep test.",m:2,p:4},
{cat:"versus",tier:"party",t:"Wie kan de hardste boer laten?",m:1,p:3},
{cat:"versus",tier:"party",t:"Dance battle: 15 sec elk. Groep stemt.",m:2,p:4},
{cat:"versus",tier:"party",t:"Wie kan het snelst 5 landen opnoemen die beginnen met dezelfde letter?",m:2,p:4},
{cat:"versus",tier:"party",t:"Wie maakt het grappigste gezicht?",m:1,p:3},
{cat:"versus",tier:"party",t:"Wie kan het langst AAAAAH roepen zonder adem te halen?",m:1,p:3},
{cat:"versus",tier:"party",t:"Coin flip duel: raad kop of munt. Best of 5.",m:1,p:3},
{cat:"versus",tier:"party",t:"Wie kent meer biermerken? Beurtelings noemen, wie herhaalt of stopt verliest.",m:1,p:3},
{cat:"versus",tier:"party",t:"Wie kan het snelst 3 tongue twisters zeggen?",m:2,p:4},
{cat:"versus",tier:"party",t:"Compliment-battle: wie geeft het betere compliment aan een vreemde? Groep stemt.",m:2,p:4},
{cat:"versus",tier:"party",t:"Wie kan het langst zijn adem inhouden?",m:1,p:3},
{cat:"versus",tier:"flirty",t:"Wie verzint de betere pickup line voor een onbekende? Groep stemt.",m:2,p:4},
{cat:"versus",tier:"flirty",t:"Staarwedstrijd: kijk de ander verleidelijk aan. Eerste die lacht drinkt.",m:2,p:4},
{cat:"versus",tier:"flirty",t:"Wie geeft het betere compliment aan de speler links? Groep stemt.",m:1,p:3},
{cat:"versus",tier:"flirty",t:"Wie kan het beste een romantische scene spelen? 15 sec.",m:2,p:4},
{cat:"versus",tier:"flirty",t:"Wie stuurt de betere openingszin naar een match? Groep stemt.",m:2,p:4},
{cat:"versus",tier:"flirty",t:"Wie doet de meest verleidelijke lip bite? Groep beoordeelt.",m:2,p:4},
{cat:"versus",tier:"flirty",t:"Wie kan het beste flirten met de barman? De ander beoordeelt.",m:2,p:4},
{cat:"versus",tier:"flirty",t:"Wie maakt de betere blue steel look?",m:1,p:3},
{cat:"versus",tier:"flirty",t:"Wie kan het beste slaapkamer-ogen doen?",m:2,p:4},
{cat:"versus",tier:"flirty",t:"Wie doet de meest overtuigende filmzoen in de lucht?",m:2,p:4},
{cat:"versus",tier:"flirty",t:"Wie schrijft het betere datingprofiel in 15 sec?",m:2,p:4},
{cat:"versus",tier:"flirty",t:"Wie kan het beste langzaam lopen alsof het een parfumreclame is?",m:2,p:3},
{cat:"versus",tier:"flirty",t:"Wie geeft de betere schouder-massage aan een speler naar keuze? 10 sec.",m:2,p:3},
{cat:"versus",tier:"flirty",t:"Wie fluistert het meest overtuigende lieve ding in iemands oor?",m:2,p:4},
{cat:"versus",tier:"flirty",t:"Wie doet de betere model op een boot-pose?",m:1,p:3},
{cat:"versus",tier:"extreme",t:"Wie durft het langst zijn telefoon te laten door de groep? Kip = drink 5.",m:3,p:5},
{cat:"versus",tier:"extreme",t:"Wie eet het snelst iets zuur of spicy?",m:2,p:4},
{cat:"versus",tier:"extreme",t:"Wie durft het meest extreme bericht te sturen? Groep beoordeelt.",m:3,p:5},
{cat:"versus",tier:"extreme",t:"Wie houdt het langst een ijsblokje in zijn hand?",m:2,p:4},
{cat:"versus",tier:"extreme",t:"Wie durft het hardst te schreeuwen op het terras?",m:2,p:4},
{cat:"versus",tier:"extreme",t:"Wie belt als eerste een willekeurig contact en zegt Ik hou van je?",m:3,p:5},
{cat:"versus",tier:"extreme",t:"Wie post als eerste een genante selfie op Instagram?",m:3,p:5},
{cat:"versus",tier:"extreme",t:"Wie durft zijn drankje in 1x te finishen?",m:2,p:4},
{cat:"versus",tier:"extreme",t:"Shot-duel: 2 shots klaar, wie drinkt het snelst.",m:2,p:4},
{cat:"versus",tier:"extreme",t:"Wie laat als eerste een vreemde lachen? Race.",m:2,p:4},
{cat:"versus",tier:"extreme",t:"Wie durft het langst een plank te houden?",m:2,p:4},
{cat:"versus",tier:"extreme",t:"Wie schrijft als eerste een bericht naar hun ex? Kip = drink 5.",m:3,p:5},
{cat:"versus",tier:"extreme",t:"Wie houdt het langst een glimlach zonder te lachen?",m:1,p:3},
{cat:"versus",tier:"extreme",t:"Wie eet als eerste een hele citroen-schijf?",m:2,p:4},
{cat:"versus",tier:"extreme",t:"Wie vraagt als eerste een vreemde om te dansen? Race.",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie doet de betere sexy dance? Groep stemt.",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie maakt het overtuigendste kreun-geluid? Groep beoordeelt.",m:3,p:5},
{cat:"versus",tier:"spicy",t:"Staarwedstrijd: wie kan het langst de ander aanstaren zonder te lachen. Verleidelijk.",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie bijt het sexiest op zijn lip? Groep stemt.",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie doet de betere slaapkamer-stem? 10 sec elk.",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie geeft de betere dirty-talk one-liner?",m:3,p:5},
{cat:"versus",tier:"spicy",t:"Wie doet de meest overtuigende lap dance in de lucht staand?",m:3,p:5},
{cat:"versus",tier:"spicy",t:"Wie noemt als eerste 5 stand-namen?",m:2,p:3},
{cat:"versus",tier:"spicy",t:"Wie doet de betere verleidelijke blik? Groep stemt.",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie geeft de betere massage aan een speler naar keuze? 15 sec.",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie vertelt het betere ergste date-verhaal?",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie maakt het betere flirt-geluid?",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie doet de sexieste push-up? 5 stuks.",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie fluistert het meest verleidelijke in het oor van een speler? Die beoordeelt.",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie beschrijft het beste een romantische scene? 15 sec.",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie doet de betere net wakker-blik? Groep stemt.",m:1,p:3},
{cat:"versus",tier:"spicy",t:"Wie beweegt het sexiest met een drankje in de hand naar muziek?",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie zegt Kom hier het meest verleidelijk?",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie maakt het betere ik wil je-gezicht?",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie vertelt het betere mijn wildste nacht-verhaal? 30 sec elk.",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie eet een aardbei het meest verleidelijk?",m:2,p:3},
{cat:"versus",tier:"spicy",t:"Wie drinkt zijn drankje het meest sexy? Groep beoordeelt.",m:2,p:3},
{cat:"versus",tier:"spicy",t:"Wie doet de betere ik check je uit-blik?",m:2,p:4},
{cat:"versus",tier:"spicy",t:"Wie beschrijft het kinkiest scenario in 10 woorden?",m:3,p:5},
{cat:"versus",tier:"spicy",t:"Wie noemt als eerste 3 dingen die ze sexy vinden aan de ander?",m:2,p:4},
{cat:"groep",tier:"party",t:"Mexicaanse golf: iedereen drinkt 1 slok na elkaar, zo snel mogelijk rond. Langzaamste drinkt 3 extra."},
{cat:"groep",tier:"party",t:"Fluisterspel: de eerste persoon fluistert een zin, de laatste zegt het hardop. Klopt het niet? Eerste en laatste drinken."},
{cat:"groep",tier:"party",t:"Iedereen noemt 1 ding dat hij vandaag heeft gedaan. Wie herhaalt of stopt: drinkt 3."},
{cat:"groep",tier:"party",t:"De hele groep moet tegelijk PROOST roepen. Wie te vroeg of te laat is: drinkt 2."},
{cat:"groep",tier:"party",t:"Iedereen neemt 1 slok. Wie het langst wacht: drinkt 3 extra."},
{cat:"groep",tier:"party",t:"Truth circle: iedereen zegt 1 eerlijk ding over de speler rechts. Geen weigerrecht."},
{cat:"groep",tier:"party",t:"De hele groep doet een Mexicaanse golf maar met een high-five. Wie mist: drinkt 2."},
{cat:"groep",tier:"party",t:"Iedereen staat tegelijk op en wisselt van stoel. Wie als laatste zit: drinkt 3."},
{cat:"groep",tier:"party",t:"Synchrone dans: de hele groep doet dezelfde move. Wie eruit valt: drinkt 2."},
{cat:"groep",tier:"party",t:"Snelste vinger: wie als eerste zijn neus aanraakt als iemand TOUCH roept. Langzaamste drinkt."},
{cat:"groep",tier:"party",t:"Iedereen vertelt zijn meest random feit. De groep stemt: meest saaie drinkt 3."},
{cat:"groep",tier:"party",t:"Gezamenlijke toast: iedereen zegt beurtelings 1 woord om een toast-zin te maken."},
{cat:"groep",tier:"party",t:"Reverse alphabet: beurtelings het alfabet achterstevoren. Wie fout gaat: drinkt."},
{cat:"groep",tier:"party",t:"Iedereen doet 1 imitatie van een dier. De slechtste drinkt 3."},
{cat:"groep",tier:"party",t:"Naam-associatie: beurtelings een beroemdheid noemen. Volgende begint met de laatste letter. Wie stopt: drinkt."},
{cat:"groep",tier:"party",t:"De hele groep houdt tegelijk adem in. Wie het eerst ademt: drinkt 3."},
{cat:"groep",tier:"party",t:"Iedereen noemt 1 reden waarom deze vakantie top is. Minst creatieve drinkt 2."},
{cat:"groep",tier:"party",t:"Gezamenlijk verhaal: iedereen zegt 1 zin om een verhaal te maken. Wie het verhaal verpest drinkt 2."},
{cat:"groep",tier:"party",t:"Iedereen raadt hoeveel uur schermtijd de speler links heeft. Dichtst bij = deelt 3 uit. Verst weg = drinkt 3."},
{cat:"groep",tier:"flirty",t:"Iedereen noemt de aantrekkelijkste eigenschap van de speler rechts."},
{cat:"groep",tier:"flirty",t:"De hele groep swipt op dezelfde Tinder-foto. Wie swipt als eerste links? Drinkt."},
{cat:"groep",tier:"flirty",t:"Iedereen vertelt in 1 zin hun slechtste date. De groep stemt: ergste = deelt 3 uit."},
{cat:"groep",tier:"flirty",t:"Iedereen doet een knipoog naar de speler tegenover. Meest awkward drinkt 2."},
{cat:"groep",tier:"flirty",t:"Compliment-ronde: iedereen geeft de speler links een oprecht compliment. Minst overtuigende drinkt 2."},
{cat:"groep",tier:"flirty",t:"Iedereen beschrijft hun type in 3 woorden. De groep matcht wie bij wie past."},
{cat:"groep",tier:"flirty",t:"Iedereen doet tegelijk hun meest verleidelijke blik. Groep stemt wie wint."},
{cat:"groep",tier:"flirty",t:"Rate the player: iedereen schrijft een score 1-10 voor de speler links. Gemiddelde wordt voorgelezen."},
{cat:"groep",tier:"flirty",t:"Iedereen fluistert de speler rechts het liefste dat ze over die persoon denken."},
{cat:"groep",tier:"flirty",t:"De hele groep beoordeelt elkaars smolder-blik. Winnaar deelt 5 uit."},
{cat:"groep",tier:"extreme",t:"Iedereen legt zijn telefoon op tafel. Iemand belt een willekeurig nummer. Wiens telefoon gaat: drinkt 5."},
{cat:"groep",tier:"extreme",t:"Shot-roulette: 1 shot water, rest echt. Wie de water krijgt: drinkt nogmaals."},
{cat:"groep",tier:"extreme",t:"Iedereen drinkt zijn drankje tot precies de helft. Wie het dichtst bij de helft zit: deelt uit."},
{cat:"groep",tier:"extreme",t:"Iedereen zet zijn telefoon op tafel. Elke notificatie die binnenkomt: eigenaar drinkt 1."},
{cat:"groep",tier:"extreme",t:"Flip cup: iedereen drinkt en flipt zijn glas. Laatste drinkt 3 extra."},
{cat:"groep",tier:"extreme",t:"Iedereen stopt 1 euro in de pot. Steen-papier-schaar-toernooi. Winnaar krijgt de pot."},
{cat:"groep",tier:"extreme",t:"Iedereen vertelt het ergste dat ze ooit hebben gestolen. De groep stemt: ergste drinkt 3."},
{cat:"groep",tier:"extreme",t:"Chain reaction: eerste persoon drinkt 1, volgende 2, volgende 3 tot iemand stopt. Die drinkt het totaal."},
{cat:"groep",tier:"extreme",t:"Power hour: iedereen neemt elke minuut 1 slok. Wie stopt: drinkt 5 als straf."},
{cat:"groep",tier:"extreme",t:"Truth or drink: de groep stelt 1 vraag aan elke speler. Niet antwoorden = drink 3."},
{cat:"groep",tier:"extreme",t:"Iedereen raadt de body count van de speler links. Meest verkeerde schatting drinkt."},
{cat:"groep",tier:"extreme",t:"Iedereen vertelt wat het ergste is dat ze hebben gedaan deze vakantie. De groep stemt."},
{cat:"groep",tier:"extreme",t:"Gezamenlijk atje: iedereen trekt tegelijk een atje. Wie het langzaamst is: drinkt 3 extra."},
{cat:"groep",tier:"extreme",t:"Alle telefoons in het midden. Eerste notificatie: iedereen leest het hardop voor. Eigenaar drinkt 3."},
{cat:"groep",tier:"extreme",t:"Iedereen neemt een shotje. Laatste die zijn glas neerzet: bestelt het volgende rondje."},
{cat:"groep",tier:"genart",t:"Iedereen vertelt hun meest genante bijnaam ooit."},
{cat:"groep",tier:"genart",t:"Iedereen doet tegelijk hun ik ga over mijn nek-gezicht. Groep stemt wie het meest overtuigend is."},
{cat:"groep",tier:"genart",t:"Iedereen vertelt het genantste liedje waar ze stiekem van houden. Groep stemt meest cringe."},
{cat:"groep",tier:"genart",t:"Iedereen moet 10 sec dansen alsof niemand kijkt. Groep stemt wie het meest geniet."},
{cat:"groep",tier:"genart",t:"Iedereen doet de meest genante pose. Foto wordt genomen."},
{cat:"groep",tier:"genart",t:"Iedereen leest hun laatste verzonden emoji-reeks voor en legt de context uit."},
{cat:"groep",tier:"genart",t:"Iedereen vertelt hun guilty pleasure-eten. Meest random drinkt 2."},
{cat:"groep",tier:"genart",t:"Iedereen laat hun meest recente selfie zien. Groep stemt wie het slechtst is."},
{cat:"groep",tier:"genart",t:"Iedereen probeert tegelijk te niezen. Meest nep drinkt 2."},
{cat:"groep",tier:"genart",t:"Iedereen vertelt het raarste dat ze doen als ze alleen zijn."},
{cat:"groep",tier:"spicy",t:"Iedereen noemt hun body count. Niet zeggen = drink 5."},
{cat:"groep",tier:"spicy",t:"Iedereen beschrijft hun type in 1 zin. Groep matcht wie bij wie past."},
{cat:"groep",tier:"spicy",t:"Iedereen noemt de sexiest persoon in de ruimte niet aan tafel."},
{cat:"groep",tier:"spicy",t:"Iedereen doet tegelijk hun slaapkamer-ogen. Groep stemt wie wint."},
{cat:"groep",tier:"spicy",t:"Iedereen noemt het raarste dat ze aantrekkelijk vinden. Meest weird drinkt 2."},
{cat:"groep",tier:"spicy",t:"Iedereen vertelt hun ergste ochtend na een one-night-stand-verhaal."},
{cat:"groep",tier:"spicy",t:"Iedereen swipt door de Tinder van de speler links voor 30 sec."},
{cat:"groep",tier:"spicy",t:"Iedereen noemt hun biggest turn-on. Groep identificeert patronen."},
{cat:"groep",tier:"spicy",t:"Iedereen vertelt het gekste compliment dat ze ooit hebben gekregen."},
{cat:"groep",tier:"spicy",t:"Iedereen beantwoordt: wat is het langste dat je ooit hebt ge-sext?"},
{cat:"groep",tier:"spicy",t:"De hele groep rated de speler rechts als sekspartner 1-10, anoniem op servet."},
{cat:"groep",tier:"spicy",t:"Iedereen vertelt het raarste dat ze ooit in bed hebben meegemaakt."},
{cat:"groep",tier:"spicy",t:"Iedereen noemt hun meest cringe flirt-poging ooit."},
{cat:"groep",tier:"spicy",t:"Iedereen beschrijft hun ideale avond maar het mag zo spicy als je wilt."},
{cat:"groep",tier:"spicy",t:"Iedereen doet een sexy walk naar de bar en terug. Groep stemt wie wint. Verliezer bestelt een ronde."},
];
export const EINDSTRAFFEN=[
"De hele groep mag elk 1 bericht sturen vanaf jouw telefoon.",
"Drink een mix-drankje dat de groep voor je maakt. Helemaal op.",
"Geef je telefoon 5 minuten aan de winnaar. Alles mag behalve verwijderen.",
"De groep kiest je profielfoto voor 24 uur.",
"Post een story die de groep typt. Mag pas na 24u weg.",
"Bel je laatst gebelde contact en vertel dat je net bent aangehouden. 15 sec volhouden.",
"Loop een rondje om het gebouw terwijl je schreeuwt dat je de verliezer bent.",
"Neem 2 atjes achter elkaar. De groep telt af.",
"De winnaar bepaalt wat jij de rest van de avond drinkt.",
"De winnaar mag 3 vragen stellen die je 100% eerlijk beantwoordt. Geen weigerrecht.",
"Drink uit je schoen.",
"Zing het refrein van een liedje dat de groep kiest, staand op een stoel.",
"Laat iedereen een DM sturen vanaf jouw Instagram.",
"De groep bepaalt je volgende bestelling en je moet het helemaal op.",
"Laat de groep je screensaver en achtergrond kiezen voor 48 uur.",
"Trek je shirt binnenstebuiten en draag het zo de rest van de avond.",
"Doe 50 push-ups op het terras. Nu. De groep filmt.",
"Stuur je ouders: Ik moet jullie morgen iets vertellen. Geen context.",
"Laat de winnaar een tweet of post plaatsen op jouw account.",
"Drink een shot dat de groep samenstelt uit alles wat op tafel staat.",
"Draag je sokken over je schoenen de rest van de avond.",
"Neem een selfie met de meest random vreemde en post het als story.",
"Bel je ex en zeg: Ik denk dat ik een fout heb gemaakt. Hang na 5 sec op.",
"Laat je wenkbrauwen tekenen door de groep met een stift.",
"Vertel je diepste geheim aan de hele tafel.",
"De winnaar mag je bio herschrijven op alle social media.",
"Drink 5 shotjes achter elkaar. De groep kiest welke.",
"Stuur Ik ben zwanger of Je wordt vader naar iemand die de groep kiest. Na 2 min: grapje.",
"De groep bepaalt een woord dat je de rest van de avond in elke zin moet gebruiken.",
"Doe alsof je huilt en bel een vriend: Ik heb alles verpest. 20 sec volhouden.",
"Ga naar de bar en bestel het drankje van de verliezer - de barman mag kiezen.",
"Laat de winnaar 3 berichten sturen vanaf jouw WhatsApp.",
"Doe 100 jumping jacks op het terras.",
"Stuur een spraakbericht van 30 sec naar je familiegroep waarin je een ballade zingt.",
"De groep kiest een outfit-element dat je de rest van de avond draagt.",
"Vertel de barman dat je verliezer bent van een drinkspel en vraag om medelijden-korting.",
"Ga naar 3 verschillende tafels en bied je excuses aan voor gisteren.",
"Maak een video voor je story: Ik ben de verliezer van NightShift. AMA.",
"Laat de groep een voice note opnemen die je naar je moeder stuurt.",
"Post een foto van je voeten met Verkoop DM als caption.",
"Ruil een kledingstuk met de winnaar voor de rest van de avond.",
"De groep mag 5 minuten alles vragen. Je moet 100% eerlijk antwoorden.",
"Stuur een hartje naar je 5 meest recente gesprekken. Alle 5. Nu.",
"Doe een handstand of poging tegen de muur terwijl de groep filmt.",
"De winnaar mag 1 DM sturen vanaf jouw datingapp.",
"Stuur een voice note naar je baas: Ik kijk uit naar maandag. Niets meer.",
"Doe alsof je een slechte stripper bent. 15 sec. De groep filmt.",
"De groep bedenkt een tattoo die je met stift op je arm zet.",
"Bel een willekeurig contact en zing het volkslied. Volledig.",
"Laat de winnaar je Tinder-account 5 minuten beheren. Swipen en berichten sturen.",
"Ga naar een vreemde tafel en doe alsof je tot hun groep behoort. Minstens 1 min.",
"Post een story-poll: Moet ik iets genants dat de groep kiest? Ja of Nee.",
"Trek een atje, gevolgd door een shotje, gevolgd door nog een atje. De groep telt.",
"Vertel de groep het genantste dat je ooit hebt gedaan op vakantie. Heel eerlijk.",
"Laat de groep kiezen: 10 push-ups, 2 atjes, of je telefoon 10 min afgeven.",
];
export const DICE_FX_POOL=[
"Drink 2 slokken of doorschuiven: iemand anders drinkt 4.",
"Kies iemand die 3 drinkt.",
"Iedereen drinkt 2.",
"DUEL - kies tegenstander, laagste worp drinkt 5.",
"Neem een atje.",
"JACKPOT - deel 8 slokken uit en kies iemand voor een atje.",
"Waterval: iedereen begint te drinken, jij stopt als eerste, dan mag de volgende stoppen, etc.",
"Dubbelgooi: gooi nog een keer. Uitkomst x2.",
"De speler links van je drinkt 4.",
"Kies 2 spelers: zij drinken elk 3.",
"Oogcontact-ronde: wie het eerst knippert drinkt 3.",
"Shot-roulette: iedereen giet een beetje van zijn drankje in 1 glas. Jij drinkt het.",
"Kaartje trekken: zwart = jij drinkt 3, rood = jij deelt 3 uit.",
"Buddy-round: kies een buddy, alles wat jij drinkt, drinkt hij ook tot volgende ronde.",
"Social: iedereen met een telefoon in zijn hand drinkt 2.",
"Reverse: de speler rechts krijgt jouw beurt.",
"Viking-mode: jij bent 1 minuut de Viking. Je mag iedereen laten drinken die je aankijkt.",
"Hot seat: de groep mag 1 minuut vragen stellen. Niet antwoorden = drink 2 per vraag.",
"Coin flip: kop = jij drinkt 5, munt = jij deelt 5 uit.",
"Thumb master: als je je duim op tafel legt, moet iedereen volgen. Laatste drinkt.",
"Stealth: fluister de speler rechts een opdracht. Voert hij het niet uit binnen 2 min = hij drinkt 5.",
"Immunity: je bent 1 ronde immune voor straffen.",
"Zwarte piet: je mag op elk moment in de komende 5 min iemand laten drinken. 1 keer.",
"All-in: iedereen gooit de dobbelsteen. Laagste score neemt een atje.",
];
